### ISSUE TITLE
After fresh install: Error Message when clicking the "info" button in the backend -> frontend-module

### ISSUE THREAD

**Issue by leine-weber** [contao-themes-net/mate-theme-bundle#1]
I'm receiving the folloowing error message: 

 Internal Server Error
Was ist das Problem?

An exception occurred while executing 'SELECT `title` AS value FROM tl_grid WHERE id='0' LIMIT 0,1': SQLSTATE[42S02]: Base table or view not found: 1146 Table '*******.tl_grid' doesn't exist.

**Comment by MDevster** [comment]
Please check if a database update is necessary in the install tool.

**Comment by MDevster** [comment]
Are other extensions installed or was the database migrated from a Contao 3 version?
Please post yout composer.json

**Comment by MDevster** [comment]
I think I found the problem. I made 2 pull requests on contao-boostrap.

For details see https://github.com/contao-bootstrap/grid/pull/14 and https://github.com/contao-bootstrap/grid/pull/13

Can you please check that in your installation?

**Comment by leine-weber** [comment]
It works. :-)

**Comment by MDevster** [comment]
It's already fixed in the current hotfix branch of contao bootstrap.

See [f27d7e2](https://github.com/contao-bootstrap/grid/commit/f27d7e22427c45f80832aae3765cbeede42f3f1b)
thanks to @dmolineus 😄
