### ISSUE TITLE
Contao 4.6 Upgrade bricht die Seitenanzeige

### ISSUE THREAD

**Issue by mr2017x** [contao-themes-net/mate-theme-bundle#10]
Hallo,

leider lässt sich mit dem Theme kein Upgrade auf Contao 4.6 durchführen, ich vermute, dass es an diesem liegt: ServiceNotFoundException(code: 0): The service \"theme helper.listener.inserttags\" was not found or is not public

Danke vorab

**Comment by mr2017x** [comment]
OK, folgendes schafft Abhilfe: 

vendor/pdir/contao-theme-helper-bundle/src/Resources/config/listener.yml

services:
  theme_helper.listener.insert_tags:
    class: Pdir\ThemeHelperBundle\EventListener\InsertTagsListener
    public: true
    arguments:
      - '@contao.framework'

**Comment by MDevster** [comment]
fixed in version 1.1.0 of https://github.com/pdir/contao-theme-helper-bundle
