### ISSUE TITLE
After Upgrade vom 1.97 to 2.1x Design is destroyed

### ISSUE THREAD

**Issue by mr2017x** [contao-themes-net/mate-theme-bundle#105]
Hi,

after Upgrade from Mate 1.97 to 2.18 (but also before) design seems to be destroyed (head navigation show also mobile Menu under the main menu (only "global" affected, left pane seems to be ok). On "main/start" page also head navigation is sorted under the slider (hero image and switch fields).

Contao 4.13.4

**Comment by MDevster** [comment]
Have you seen the update section in the documentation? There were a few changes to the templates in version 2.
https://pdir.de/docs/de/contao/themes/mate/update/

**Comment by mr2017x** [comment]
> Have you seen the update section in the documentation? There were a few changes to the templates in version 2. https://pdir.de/docs/de/contao/themes/mate/update/

Hi, yes i checked it but this didn't help so far. it looks as in several conditions the navigation element swaps under the hero image(s)
