### ISSUE TITLE
Not possible to install!

### ISSUE THREAD

**Issue by mochitoju** [contao-themes-net/mate-theme-bundle#106]
Lässt sich nicht auf eine nagelneue Contao 4.9.29 Installation 
einbinden.

- contao-bootstrap/grid 2.4.0 requires php ^7.4 || ^8.0 -> your php version (7.3.10.0) does not satisfy that requirement.
- contao-themes-net/mate-theme-bundle 2.18.0 requires contao-bootstrap/grid ^2.4 -> satisfiable by contao-bootstrap/grid[2.4.0].
- Root composer.json requires contao-themes-net/mate-theme-bundle ^2.18 -> satisfiable by contao-themes-net/mate-theme-bundle[2.18.0].

- Bootstrap kann ich nicht updaten
- PHP kann ich max. 7.3.23 bieten (sagt aber 7.1 als minimum!)
-

**Comment by Ernestopheles** [comment]
php 7.3 kriegt keine sicherheitsupdates mehr, das solltest du nnicht mehr verwenden!

ich habe mate 2.17 mit bootstrap 2.3 laufen, gehe aber demnächst auf mate 3 (wird gerade getestet) , das kein bootstrap mehr benötigt. ich vermute, dass auch 2.18 mit dem bootstrap 2.3 läuft.

**Comment by mochitoju** [comment]
Danke für die schnelle Info, bei DF steht mir aktuell nur 7.3x zur Verfügung. 
Gibt es eine Möglichkeit es ohne den Manager zu installieren/zu verwenden?

**Comment by Ernestopheles** [comment]
was ist df?
die art der installation spielt keine rolle.
empfehle dir update php

**Comment by mochitoju** [comment]
DF= DomainFactory
update.php - wo finde ich diese? Hab nur den "Contao-Manager"

**Comment by Ernestopheles** [comment]
![DeepinBildschirmfoto_Bereich auswählen_20220529155608](https://user-images.githubusercontent.com/7561403/170872700-44cd0b16-ab25-4e78-a957-27bfc4af93ae.png)

**Comment by mochitoju** [comment]
Danke, ist klar. Aber es gibt keine Möglichkeit (ohne meinen Hoster) aktuell das Mate zu installieren?

**Comment by MDevster** [comment]
@mochitoju Du müsstest eine frühere Version des MATE Themes verwenden und explizit diese Version anfordern. Es kann sein, dass du auch für `contao-bootstrap/grid` eine ältere Version anfordern musst.

    "require": {
          "contao-themes-net/odd-theme-bundle": "2.17.6",
          "contao-bootstrap/grid": "2.3.1",
    }

Sobald eine neuere PHP-Version bei deinem Hosting zur Verfügung steht, musst du die Versionen für eine Update wieder anpassen.
