### ISSUE TITLE
Add more levels to dropdown menu

### ISSUE THREAD

**Issue by MicioMax** [contao-themes-net/mate-theme-bundle#11]
Hi,

I've seen that dropdown menu is limited to one sublevel; on default (contao) navigation menu is possible to have more nested pages correctly displayed as submenus on dropdown.
It is possible to add this feature to mate menu ?
To clarify : 
I have following page structure : 
`

    products

        boards

             board1

             board2

        shields

             shield1

             shield2
`
Default contao navigation menu builds (correctly) the full navigation structure on html page; the mate one brings only products, board and shields with no nested menu in boards and shields.
It's not a css problem, the html for nested lists is not generated.

**Comment by badde-media** [comment]
Still not working. Needs to be configured?

**Comment by MicioMax** [comment]
I modified hardly both the templates and the css, to get it working.
You can see it here : www.fishino.com.
Sincerely I don't remember which files I patched, they're now a mix of mate theme and previous one, with menus running on pure css, so almost nothing to do with original code.
My first trials keeping original mate code were unsuccesfull.

**Comment by seibtph** [comment]
Now we have added the third level dropdown navigation in version 2.1.0.
