### ISSUE TITLE
Multi-Domain Setup - Documentation outdated

### ISSUE THREAD

**Issue by mrflory** [contao-themes-net/mate-theme-bundle#112]
## Bug description
The multi-domain setup documentation is outdated (https://pdir.de/docs/de/contao/themes/mate/customization/multiple_domains/).

## Steps to reproduce
Follow documentation, in step 2 line 22 should be `$combiner->add('files/mate/sass/domain2/mate.scss');` but it is `<meta property="og:description" content="<?php echo $this->description; ?>" />`. I don't know what line to edit to make it work.

**Comment by MDevster** [comment]
Please update to Version 2.19.6 and see updated documentation https://pdir.de/docs/de/contao/themes/mate/customization/multiple_domains/
