### ISSUE TITLE
Nach Update auf 2.19.3 werden Seiten, die nur für Gäste sichtbar sein sollen, angezeigt, wenn der Anwender eingeloggt ist.  

### ISSUE THREAD

**Issue by Ernestopheles** [contao-themes-net/mate-theme-bundle#114]
contao 4.13, php 8.0

**Comment by Ernestopheles** [comment]
Die Seiten werden im Hauptmenü angezeigt und auch bei Aufruf. Habe einen Hauptmenüpunkt, der nur für Gäste sichtbar sein soll.

**Comment by Ernestopheles** [comment]
Aber ich denke es ist dennoch ein Bug, und - so wie ich es verstanden habe - ist die Option "Nur Gästen anzeigen" in 4.13 zwar redundant (zu Seite schützen - Gäste), sollte aber dennoch wirksam werden.

**Comment by MDevster** [comment]
Fixed in version 2.19.4.
