### ISSUE TITLE
Exception in Contao 4.9 and Mate Theme 2.19.2 and higher

### ISSUE THREAD

**Issue by Songworks** [contao-themes-net/mate-theme-bundle#116]
## Bug description
Hi there,

after updating a Contao 4.9 (to 4.9.34) and the Mate Theme to 2.19.3 we got an exception thrown:

```
Attempted to call an undefined method named "getPublishedSubpagesByPid" of class "ContaoThemesNet\MateThemeBundle\Mate\NavBarModule".
```

Method call is [here](https://github.com/contao-themes-net/mate-theme-bundle/blob/master/src/Resources/contao/modules/Mate/NavBarModule.php#L221).

As far as I could gather in the short time I had to debug this, the `getPublishedSubpagesByPid`-Method is only available in Contao 4.13 and not 4.9 (yet?)?

mate-theme-bundle version 2.19.1 still works though, so it's something newish.

## Steps to reproduce
n/a

## Expected behavior
No exception thrown. :o)

## Screenshots
n/a

## Environment
PHP 7.4.30
Contao 4.9.34
mate-theme-bundle 2.19.3

Thanks and cheers!

**Comment by MDevster** [comment]
Fixed in [2.19.5](https://github.com/contao-themes-net/mate-theme-bundle/releases/tag/2.19.5)
