### ISSUE TITLE
Folders appear in sitemap.xml due to old contao-folderpage 2.x dependency

### ISSUE THREAD

**Issue by mrflory** [contao-themes-net/mate-theme-bundle#119]
## Bug description
The folders in the site structure appear in sitemap.xml. This is an old bug of folderpage: https://github.com/terminal42/contao-folderpage/issues/24. Update of folderpage not possible as version is locked to 2.x and bug is fixed in 3.x.

## Steps to reproduce
Is available in demo: https://mate.pdir.de/sitemap.xml -> `<loc>https://mate.pdir.de/105.html</loc>`

## Expected behavior
Folders (as well as content sites header, footer and modules) do not appear in sitemap.xml / I can update folderpage to the newest version.

## Screenshots
n/a

## Environment
Contao 4.13.10

**Comment by MDevster** [comment]
Fixed in version 2.19.7 for Contao 4.x. Was already fixed in branch 3.x for Contao 5.

**Comment by mrflory** [comment]
Thanks very much for the quick fix! The same issue occurs in nature-theme. Should I create a new issue there?

**Comment by seibtph** [comment]
We will fix this in nature theme and in all other themes. You don't need to create a new issue.
