### ISSUE TITLE
Installation: Initial demo data migration - MATE Theme: Database changes can´t apply

### ISSUE THREAD

**Issue by meRitAton17** [contao-themes-net/mate-theme-bundle#126]
First installation contao5 with MATE Theme without any other content in database. Last step install demo data failed with message:
Changes could not apply...Please check and try again.
Server: PHP 8.1.7; Maria DB 10.x
How can I install initial demo data?
![fehler-contao](https://user-images.githubusercontent.com/89604656/199594954-e5bd5e2f-08f6-4a8e-9fce-07568bc4e1c9.PNG)

**Comment by MDevster** [comment]
@meRitAton17 Do you have a way to do the database changes via SSH? What is the output of the `vendor/bin/contao-console contao:migrate -vvv` command?

**Comment by 2dikkie6** [comment]
Hi, I have exactly the same problem as meRitAton17 describes. Below my error output.

[error.txt](https://github.com/contao-themes-net/mate-theme-bundle/files/9929285/error.txt)

**Comment by seibtph** [comment]
Is the database completely empty (except for tl_user)?

**Comment by MDevster** [comment]
Unfortunately we can't recreate the error, neither with mySql nor with MariaDB. We would need more information about the hosting or web hosting package. Or would it be possible to get access to the test installation?

**Comment by 2dikkie6** [comment]
Hi Mathias,

My contao website is hosted at Neostra (with php8.1 and MariaDB 10)
I can send you the accounts (backend and manager) to login to  my test site.

Kind regards,
Dik

Van: Mathias Arzberger ***@***.***>
Verzonden: donderdag 3 november 2022 17:56
Aan: contao-themes-net/mate-theme-bundle ***@***.***>
CC: 2dikkie6 ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [contao-themes-net/mate-theme-bundle] Installation: Initial demo data migration - MATE Theme: Database changes can´t apply (Issue #126)


Unfortunately we can't recreate the error, neither with mySql nor with MariaDB. We would need more information about the hosting or web hosting package. Or would it be possible to get access to the test installation?

**Comment by MDevster** [comment]
Please use **support** AT **pdir** PUNKT **de** to send credentials and reference this issue.

**Comment by seibtph** [comment]
@meRitAton17 Can you please try to delete all files in the file management, synchronize and execute the migrations again? Or clear the table tl_files in the database. For @2dikkie6 this worked.

**Comment by meRitAton17** [comment]
@seibtph: Thank you very much! Delete the table tl_files solves the installproblem. The installation process for the mate theme rebuilt table tl_files and the installation don´t shows any errors.
But unfortunately, the site itself don´t work. 
(FireFox):Developer-Tools Console shows: This error page has no error code in its security info.
Chrome:Developer-Tools Console shows:  crbug/1173575, non-JS module files deprecated.    VM128:6789
 (anonymous) @ VM128:6789
 My Domain:  https://contao19.soft-fabrik.de/
 
 @MDevster : Thank you for your tipps, but unfortunately I don´t know how to create the vendor/bin/contao-console contao:migrate -vvv command. I work with the database via mysqladmin, not ssh

**Comment by meRitAton17** [comment]
Problem is solved. Protocol for startpage was http. Change to https and all is fine :-))
