### ISSUE TITLE
Mate 3.0.0/contao5: Farbschema lässt sich nicht anpassen

### ISSUE THREAD

**Issue by meRitAton17** [contao-themes-net/mate-theme-bundle#129]
Ein Wechsel des Standard-Farbschemas durch Entfernen der Kommentierung in Zeile 18 - 20 der Datei _custom_colors.scss bewirkt gar nichts. Es bleibt alles im Standard-grün. Wie kann ich die Farbpalette Indigo verwenden?

**Comment by seibtph** [comment]
Kannst du die Seite mal mit Strg + F5 neuladen?

Du hast den mate-Ordner auch nicht umbenannt? Wir hatten das schon öfter, dass Ordner umbenannt wurden und dann die Dateien nicht mehr geladen werden. Der Pfad zur Datei muss genauso aussehen: mate/sass/_custom_colors.scss

Ansonsten kannst du mal den Inhalr der _custom_colors.scss hier reinposten.

Leider konnte ich das Problem noch nicht nachstellen, in unserer Testumgebung funktioniert es.

**Comment by meRitAton17** [comment]
Das Neuladen verändert die Seite nicht. Der Pfad ist /contao19.soft-fabrik.de/files/mate/sass/_custom_colors.scss.
Auch ein Entfernen der Kommentar-slashs für die Zeilen 28 - 32 zeigt keine Wirkung. Habe dort erstmal willkürliche Farben angenommen, um zu sehen, ob etwas passiert:

/* ============================= */
/*     MATE Theme Variables      */
/* ============================= */

/* Colors */
$mateColor1: #9fa8da ;
$mateColor2: #0097a7 ;
$mateColor3: #ff4081;
$mateColor4: #58774e;
$mateColor6: #abbdb1;
--------------------------------------------------------------
Herzliche Grüße, und Danke, dass sich jemand kümmert.

**Comment by seibtph** [comment]
Bei mir geht es. Vielleicht kannst du uns mal einen Contao Zugang an support [AT] pdir PUNKT de senden, damit wir uns das mal näher ansehen können.

**Comment by MDevster** [comment]
@meRitAton17 Kannst du mal bitte testen ob die Änderung übernommen wird wenn du nach einer Änderung den Debug-Modus aktiv hast?

**Comment by MDevster** [comment]
@meRitAton17 Erfolgt die Änderung über die Dateiverwaltung oder per FTP/SSH?
