### ISSUE TITLE
Keine Farbänderung möglich

### ISSUE THREAD

**Issue by Kadlin** [contao-themes-net/mate-theme-bundle#13]
Habe Änderung an den Themefarbe über die Datei in der SCSS "_custom_colors.scss" gemacht; 
Jedoch funktioniert das nicht. 
Installiere Contao in der Version 4.6, mate-theme-bundle Version 1.4.0 Gemäß 
Leider ändert sich die Farbe. Wie muss die Änderung gemacht werden?

**Comment by MDevster** [comment]
Wir haben die Farbanpassungen in der Version 1.5 noch einmal vereinfacht und verbessert. Bitte update deine Version und prüfe ob es nun besser funktioniert.
