### ISSUE TITLE
Galerie MATE Theme

### ISSUE THREAD

**Issue by okni123** [contao-themes-net/mate-theme-bundle#130]
hallo
wenn ich in der Galerie bei "Sortieren nach" auf "Zufällige Reihenfolge" stelle und Elemente pro Seite begrenze, wird die Seitennavigation unten nicht angezeigt. Ändere ich auf Dateiname oder Datum auf- oder absteigend ist die Navigation sichtbar.
Ist das ein Bug.
Danke
VG

**Comment by seibtph** [comment]
In Contao 4.13 ist tatsächlich ein wahrscheinlich gewolltes Verhalten. Ich habe dazu folgenden Github-Issue gefunden: https://github.com/contao/core/issues/8033#issuecomment-148077190. Das lässt sich auch in der Contao-Demo reproduzieren. 

In Contao 5 funktioniert das ganze aber. Du müsstest also auf Contao 5 updaten, wenn dir das Feature wichtig wäre. Das MATE Theme ist im übrigen bereits für Contao 5 verfügbar.
