### ISSUE TITLE
Navbar not working proberly on touchscreen laptops when using the mouse.

### ISSUE THREAD

**Issue by Jochen2303** [contao-themes-net/mate-theme-bundle#131]
## Bug description
Since upgrade from Contao 4.8 to 4.13, the navbar is not working proberly anymore on touchscreen laptops when using the mouse.
Only the highest level is clickable on a e.g. 3-level menue with the mouseclick,

## Steps to reproduce
I  accounterd the bug on my own laptops (touchscreenable). On my Desktop (not touchscreenable) it is working fine. All menue levels are clickable with the mouse.
This can also be reproduced on the MATE Live-Demo with an touchscreenable laptop.

## Expected behavior
All menue levels should be clickable with the mouse like on Contao version 4.8

## Screenshots
Here a screenshot from the MATE live-demo.
Menue entries "ELEMENTE" and "Mate-Elemente" should be clickable. But only the last levels  "Contentbox", "Teaserbox" etc. are clickable with the mouseclick. By the way, the "ELEMENTE" menue opened automatically in Contao 4.8 when mouseover without mouse click. This is also not the case anymore.
![Mate_Issue](https://user-images.githubusercontent.com/115405319/202209988-a692dc41-4159-49fb-af69-340517458611.jpg)

## Environment
Contao 4.13.12, MATE Theme 2.19.8,  PHP8.1, Chrome, Edge, Firefox

**Comment by Jochen2303** [comment]
Additional Info to the screen shot above:
Like I've mensioned: The issue only occurs on laptops with touchscreen when using the mouse.
When I click on menu entries "ELEMENTE" or "Mate Elemente" with the mouse, nothing happens.
When I tap on the menu entries with my finger, then the respective page opens.

BR Jochen

**Comment by MDevster** [comment]
Please update, fixed in 2.19.9 or 3.0.1.

**Comment by Jochen2303** [comment]
Hi Matthias,
with Contao 4.13.13. and Mate 2.19.9 the automatically dropdown while mousover is working fine and clicking on a main menue item with mouse leads to the corresponding page.
But afterwards, the droppdown menü sticks on the page on top. See image below:

![Mate-Issue](https://user-images.githubusercontent.com/115405319/203548618-5f139a14-c36f-4016-a159-ff8a3ab20211.png)

Best Regards,
Jochen
