### ISSUE TITLE
Theme Installation in Contao 5.0.6 problem

### ISSUE THREAD

**Issue by acht11** [contao-themes-net/mate-theme-bundle#132]
## Bug description
When I try to install the Mate-Theme in Contao 5.0.6, I get an error in the last step "Database-Migration".
Same Problem with 0.1-Theme. (Initial demo data migration - 0.1 Theme) is not working.

PHP-Version 8.1
Maria-DB Version 10.5.16
Contao Version 5.0.6 fresh installation
![2022-11-18_08-38-23](https://user-images.githubusercontent.com/86398696/202648047-56904499-a05a-4cd7-80ea-a0ef33134acd.jpg)

**Comment by acht11** [comment]
thanks for the fast answers, but same problem.

**Comment by acht11** [comment]
![2022-11-18 14_10_31-Contao Manager _ contao5 acht11 de und 18 weitere Seiten - Persönlich – Microsof](https://user-images.githubusercontent.com/86398696/202712982-a39ce5f2-6223-4344-8ebe-6c3217ace86c.png)

**Comment by seibtph** [comment]
I can't reproduze this error. Would it be possible to get access to the test installation? Please use support AT pdir PUNKT de to send credentials and reference this issue.

**Comment by Jochen2303** [comment]
I had the same issue while installing Mate on Contao 5.0.6
Clear the table tl_files in the database worked for me.

Best Regards,
Jochen

**Comment by MDevster** [comment]
Please test version 3.0.1

**Comment by MDevster** [comment]
Please reopen the ticket if the error still exists.
