### ISSUE TITLE
Navbar not working proberly on touchscreen laptops when using the mouse #131 not completely fixed

### ISSUE THREAD

**Issue by Jochen2303** [contao-themes-net/mate-theme-bundle#135]
## Bug description
Issue #131 was fixed but still a problem exists.
With Contao 4.13.13. and Mate 2.19.9 the automatically dropdown while mousover is working fine again and clicking on a main menue item with mouse leads to the corresponding page.
But afterwards, the droppdown menü sticks on the page on top. 

## Steps to reproduce
Issue only happens with touchable laptops.

## Expected behavior
Dropdown should not stick on top.

## Screenshots
Clicking on a main menue item with mouse leads to the corresponding page. But afterwards, the droppdown menü sticks on the page on top.
![Mate-Issue](https://user-images.githubusercontent.com/115405319/203984218-661fded9-b736-4b42-92e9-6bf153857b14.png)

## Environment
Contao 4.13.13, MATE Theme 2.19.9, PHP8.1, Chrome, Edge, Firefox

**Comment by Samson1964** [comment]
In Contao 4.12.7 wahrscheinlich das gleiche Problem. In der Desktop-Version der Navbar wird das aktive Submenü ganz nach oben gerückt, offen angezeigt (also nicht erst bei Mouseover) und überlagert die Navbar. Der Bug entstand durch die Installation von Version 2.19.9 des Mate-Theme. Ich habe meine Installation auf 2.19.8 zurückgesetzt und danach funktionierte die Navbar wieder.

**Comment by MDevster** [comment]
Fixed in 2.19.10/3.0.2, please update!
