### ISSUE TITLE
headroom -> conflict with mootools

### ISSUE THREAD

**Issue by loadbrain** [contao-themes-net/mate-theme-bundle#14]
HI,
when activating mootools in default template there is an JS Error according JQuerys document.ready function in 
/vendor/contao-themes-net/mate-theme-bundle/src/Resources/public/js/theme.js:

`$(document).ready(function(){..`
should be replaced with
`jQuery.noConflict();
jQuery(document).ready(function ($) {`

**Comment by seibtph** [comment]
Thanks, fixed in 1.5.2
