### ISSUE TITLE
Using two content slider on one page leads to overwritten text in slide buttons

### ISSUE THREAD

**Issue by bopsoid** [contao-themes-net/mate-theme-bundle#144]
**MATE 3.0.3, Contao 5.0.7, PHP 8.1.3 on Ionos shared Linux hosting.**

Hello,

if you have two different content sliders together on one page, then the text inside the buttons below the picture will be overwritten with the titel content of the second slider.

For example:

First slider, three images with text, titles are Picture 1, Picture 2, Picture 3.

Second slider, three images with text, titles are Text 1, Text 2, Text 3.

Now on the website the buttons under BOTH content sliders show Text 1, Text 2, Text 3. Picture 1, Picture 2, Picture 3 are not showing up. Seems that there is something overwritten in the internal variable system of the content slider? Same variable names?

Pictures and text below picture are OK though.

Thanks for looking into this issue. :-)

Merry christmas,
Boris

**Comment by MDevster** [comment]
Fixed in version 3.0.5
