### ISSUE TITLE
MATE mit Contao 5 Fehlermeldung im Frontend

### ISSUE THREAD

**Issue by martinschaible** [contao-themes-net/mate-theme-bundle#147]
## Bug description
Soeben habe ich Mate auf eine frische Contao 5 Website installiert. Angepasst oder geändert habe ich noch nichts.

Beim Aufruf der Site kommt die übliche Fehlermeldung "Es ist ein Fehler aufgetreten". In der Logdatei sehe ich, dass ein Bild nicht geladen werden konnte:

[`2023-01-11T13:11:11.306275+00:00] request.CRITICAL: Uncaught PHP Exception Contao\CoreBundle\Exception\InvalidResourceException: "Could not read resource from storage: Unable to read from "files/mate/img/mate_logo.png"." at /var/www/vhosts/----/httpdocs/vendor/contao/core-bundle/src/Image/Studio/FigureBuilder.php line 281 {"exception":"[object] (Contao\\CoreBundle\\Exception\\InvalidResourceException(code: 0): Could not read resource from storage: Unable to read from \"files/mate/img/mate_logo.png\". at /var/www/vhosts/----/httpdocs/vendor/contao/core-bundle/src/Image/Studio/FigureBuilder.php:281)\n[previous exception] [object] (Contao\\CoreBundle\\Filesystem\\VirtualFilesystemException(code: 2): Unable to read from \"files/mate/img/mate_logo.png\". at /var/www/vhosts/----/httpdocs/vendor/contao/core-bundle/src/Filesystem/VirtualFilesystemException.php:65)\n[previous exception] [object] (League\\Flysystem\\UnableToReadFile(code: 0): Unable to read file from location: mate/img/mate_logo.png. fopen(/var/www/vhosts/----/httpdocs/files/mate/img/mate_logo.png): Failed to open stream: No such file or directory at /var/www/vhosts/----/httpdocs/vendor/league/flysystem/src/UnableToReadFile.php:24)"} []`

Der Ordner **files/mate/img/** ist tatsächlich leer. Was kann ich machen? 

Danke!

**Comment by seibtph** [comment]
Hallo Martin,

ich habe das mehrfach getestet, konnte das Verhalten aber nicht reproduzieren.

Du kannst versuchen die Dateien selber in der Dateiverwaltung hochzuladen. Die Dateien findest du hier: https://github.com/contao-themes-net/mate-theme-bundle/tree/master/contao/files/mate

Wurden denn die anderen Dateien im Ordner mate/sass angelegt?

**Comment by martinschaible** [comment]
Hallo Philipp

Der Ordner /files ist komplett leer. Ich habe gerade die Ordner via FTP hochgeladen und die Website funktioniert. Es fehlen noch einige Bilder, aber das kann ich sicher beheben.

Es scheint so, als wäre irgendetwas bei der Installation daneben gegangen.

Vielen Danke für Deine Hilfe.

**Comment by seibtph** [comment]
Normalerweise müssten die über die Migration (also wenn du die Datenbank aktualisierst) automatisch angelegt werden. Sehr komisch. Aber wenn es bei dir so erstmal geht ist das gut. Wir werden mal beobachten ob das nochmal auftritt.
