### ISSUE TITLE
Nachrichtenanordnung

### ISSUE THREAD

**Issue by mr2017x** [contao-themes-net/mate-theme-bundle#15]
Hallo,

vielen Dank für das Theme. Ich möchte nun allerdings die Zeitleiste andersherum angeordnet haben - sprich nicht die älteste News soll im Top-Slider (Start) ganz links sein, sondern die neueste. Wie kann ich das arrangieren?

Vielen Dank vorab!

**Comment by seibtph** [comment]
Hallo,

aktuell wird immer die aktuellste News im Slider ganz links angezeigt. In der Demo unter mate.pdir.de ist das auch so.

**Comment by seibtph** [comment]
@mr2017x In Contao 4.6 kannst du jetzt im Modul der Newsliste einstellen in welcher Reihenfolge die Beiträge angezeigt werden. In den vorherigen Versionen gab es die Einstellmöglichkeit noch nicht und da wurden die neuesten Beiträge als erstes angezeigt, in Contao 4.6 ist jetzt aber "Datum aufsteigend" voreingestellt. Wir werden das in der nächsten Version anpassen, sodass immer "Datum absteigend" voreingestellt ist.

**Comment by mr2017x** [comment]
Hallo Seibtph,

hab ich nun auch schon gefunden und mich stark gewundert, ob ich wirklich so blind war :) aber funktioniert. Danke euch!
