### ISSUE TITLE
list-style-type not correct in ce_text_simplebox_mate text boxes

### ISSUE THREAD

**Issue by chfauck** [contao-themes-net/mate-theme-bundle#150]
Hi,

I want to use Inhaltscontainer elements shown on at the bottom on [Mate Theme Live Demo](https://mate.pdir.de/layouts/layout-mit-linker-und-rechter-spalte.html) 
and found, that the list-style-type is set to "none" when using in an Inhaltscontainer.

Could you fix this isue, please?

I am using:
- ContaoManager 1.6.3
- Contao Version 5.0.10
- Mate Version 3.1.0

Thanks and regards,
Christoph

**Comment by chfauck** [comment]
Found and fixed in custom.scss:

.ce_text_simplebox_mate ul:not(.browser-default) li:before {
	content:		"»";
	color:			$mateColor2;
	font-weight:	700;

	padding-right:	15px;
	margin-left:	15px;
	position:		absolute;
	left:			0;
}

.ce_text_simplebox_mate ul:not(.browser-default) li {
	margin-left:	20px;
}

**Comment by seibtph** [comment]
Fixed in MATE theme version 3.2.0
