### ISSUE TITLE
favicon.ico path set fix in template

### ISSUE THREAD

**Issue by chfauck** [contao-themes-net/mate-theme-bundle#151]
When adding a new web site in parallel to the mate template example using mate theme, the favicon path defined within the new web site is not used in the fe.

Setting the path from `files/mate/img/favicon.ico` to `favicon.ico` in
`files/mate/img/favicon.ico to favicon.ico in /contao/vendor/contao-themes-net/mate-theme-bundle/contao/templates/layouts/mate/fe_page_mate.html5` fix this issue.

**Comment by seibtph** [comment]
In Contao 5 we remove the favicon from fe fe_page template. You can set the favicon in your root page.
