### ISSUE TITLE
Breadcrumb Navigation seit Contao 4.13.16 falsch dargestellt

### ISSUE THREAD

**Issue by mlirsch** [contao-themes-net/mate-theme-bundle#153]
Mit contao Version 4.13.16 wurde das Template der Breadcrumb Navigation geändert
[https://github.com/contao/contao/pull/5721](https://github.com/contao/contao/pull/5721)

Durch die geänderten Tags wird die Breadcrumbnavigation nicht mehr richtig dargestellt.

Environment
PHP version: 8.1
Contao Version: 4.13.18
Mate-Theme Version: 2.20.1

**Comment by seibtph** [comment]
Hast du das angepasste Template mod_breadcrumb_mate ausgewählt?
