### ISSUE TITLE
Darstellungsprobleme MATE-Theme

### ISSUE THREAD

**Issue by Envinyatar78** [contao-themes-net/mate-theme-bundle#161]
Hallo,

Außer bei SAFARI wird in allen Browsern (FF, Opera, Edge, mobiler Browser Android) 
* auf das ursprüngliche Theme zurückgegriffen (Farbwerte und teilweise Inhalt wird nicht übernommen -- Logos fehlen in Header und Footer)
* der Spider oben wird nicht dargestellt, stattdessen werden die Sliderbilder untereinander abgebildet.

Problem besteht seit 1.7. -- bitte um Hinweise!

Webseite: www.trachtenverband.bayern; Screenshot siehe anbei. (rechts: Safari, links: Opera).

Danke!

<img width="1500" alt="Bildschirmfoto 2023-07-04 um 13 31 36" src="https://github.com/contao-themes-net/mate-theme-bundle/assets/138585519/90b33e30-83da-423c-8cae-acc6f6a936db">

**Comment by seibtph** [comment]
Hast du mal probiert den Browsercache zu leeren?

**Comment by Envinyatar78** [comment]
Hey - ja hab ich, hat am Ende für die Bilder (die zunächst zwischendurch mal gar nicht eingebunden worden sind) geholfen. 
Der Rest war einfach schlampig gepflegt ;-) 
Hat sich also nach bisserl suchen und einlesen glücklicherweise erledigt, danke :-)
