### ISSUE TITLE
Anpassen Hauptmenü

### ISSUE THREAD

**Issue by marioleithner** [contao-themes-net/mate-theme-bundle#164]
Hallo, ist es möglich die Höhe des Hauptmenüs anzupassen? 
Können die Überstriche in der Navigation ausgeblendet werden?
Wo finde ich die Einstellungen hierzu?

http://cms.mr-hassgau.de.w01ce896.kasserver.com/

Vielen Dank Gruß Mario

**Comment by seibtph** [comment]
Hallo Mario,

du kannst das mittels etwas CSS in der custom.scss anpassen.

Höhe anpassen:

```
@media (min-width: 768px) {
  .mod_mateNavbar:not(.stuck) .nav-wrapper {
      min-height: 60px;
  }
}
```

Striche entfernen:

```
#header .nav-wrapper ul li a {
  &:before, &:hover:before {
    display: none;
  }
}
```
