### ISSUE TITLE
Mate Theme Bilder im News Spider werden nicht angezeigt

### ISSUE THREAD

**Issue by snips3** [contao-themes-net/mate-theme-bundle#165]
## Bug description
Ich habe das Theme Installiert und auch die Datenbank entsprechend importiert.
Leider werden aber auf der Startseite die Bilder im News Spider nicht angezeigt.

**Comment by seibtph** [comment]
Hast du einen Link zu deiner Seite? Welche Contao-Version hast du installiert? Wenn du noch Contao 4 hast: Hast du unter Systemwartung die Symlinks neu erstellt?

**Comment by seibtph** [comment]
Vielleicht liegt es auch an der fehlenden WEBP-Unterstützung.

Schau dir dazu mal unseren Blogbeitrag an: https://pdir.de/docs/de/contao/themes/mate/customization/faq/#bilder
unter **Warum werden manche Bilder nicht angezeigt? (WEBP-Unterstützung)** Lösung #2
