### ISSUE TITLE
Unknown insert tag countto

### ISSUE THREAD

**Issue by BugBuster1701** [contao-themes-net/mate-theme-bundle#168]
## Bug description
Unknown insert tag `{{countto::xxx::yyy}}`

## Steps to reproduce
Frische Installation von Contao 5.2 und Mate Theme (Version 3.2.4)

## Screenshots
![grafik](https://github.com/contao-themes-net/mate-theme-bundle/assets/1218809/ee3c4fae-6f23-482d-ba1b-f22657e2edd2)
![grafik](https://github.com/contao-themes-net/mate-theme-bundle/assets/1218809/954c40a7-4633-41db-926b-a6bca5c028d3)

## Environment
Ubuntu 
PHP 8.2.9
Contao 5.2.0

**Comment by seibtph** [comment]
Fixed in version 3.2.5
