### ISSUE TITLE
Farben anpassen

### ISSUE THREAD

**Issue by badde-media** [contao-themes-net/mate-theme-bundle#17]
Ich versuche, auf einer Webseite verschiedene Teilbereiche in den verschiedenen vorgefertigten Farbschemata anzupassen, finde aber keine Möglichkeit dies zu tun. Alle Kommentare in den SCSS Dateien wurden entfernt, aber es ändert sich nichts.

**Comment by seibtph** [comment]
Bereits per Mail geantwortet:

Zur Zeit noch nicht vom Theme vorgesehen, aber über Umwege möglich: https://github.com/pdir/contao-themes-docs/blob/master/mate-theme/farbschema-fuer-einzelne-seite-anpassen.md
