### ISSUE TITLE
MATE Themes, Bilder im Slider auf der Startseite werden nicht geladen

### ISSUE THREAD

**Issue by uwegrothe33** [contao-themes-net/mate-theme-bundle#173]
Hallo zusammen, installiert ist CONTAO 4.13.32 mit MATE Theme Version 2.20. 

URL: www.angelabehler.de

Die Bilder im Slider erscheinen nicht. Hat jemand einen Tipp?

UG

**Comment by seibtph** [comment]
Hallo Uwe,

so wie es ausschaut, hast du das bereits lösen können?
