### ISSUE TITLE
No .cto for existing Contao 5.2 Installation

### ISSUE THREAD

**Issue by TB1234** [contao-themes-net/mate-theme-bundle#174]
## Bug description
There is no existing .cto file for installation with an existing Contao later than 4.13. 

## Steps to reproduce
The official [Download link](https://pdir.de/produkthilfe.html) only offers files until 4.13.

## Environment
Contao 5.2

**Comment by seibtph** [comment]
We will provide the missing .cto soon. I'll let you know here again when it's ready.

**Comment by seibtph** [comment]
We have added the .cto files for Contao 5.3.
