### ISSUE TITLE
Inhaltselement Teaserbox mit Text/Bild nebeneinander

### ISSUE THREAD

**Issue by duessel92** [contao-themes-net/mate-theme-bundle#175]
In der Dokumentation wird die Darstellung des Inhaltselements Teaserbox auch als Text/Bild nebeneinander dargestellt und erklärt: https://pdir.de/docs/de/contao/themes/mate/elements/teaser_box/#teaserbox-mit-textbild-nebeneinander

Das ganze soll dann so aussehen: https://mate.pdir.de/cards.html

Allerdings kann ich im Backend die entsprechenden Einstellungen nicht vornehmen. Ich nutze das Mate Theme Version 3.2.5 mit Contao 5.2.4

Gibt es hierfür eine Lösung?

**Comment by MDevster** [comment]
Fixed in version 3.3.0
