### ISSUE TITLE
no picture when is installed on Alfahostings webspace

### ISSUE THREAD

**Issue by acht11** [contao-themes-net/mate-theme-bundle#178]
## Bug description
I have moved a Contao 5.2x installation with Mate-Theme from All-Inkl-provider to alfahosting.
Now I have the issue, that all the pictures, what was resized by a Mate picture size, are not displaying.
When I use "Exaktes Format" with the same sizing, on the same picture, then it works.
To rule out, that there was a problem in the installation, I installed an fresh contao with Mate-Theme. Same issue.

## Steps to reproduce
Just freh installation on Alfahosting Webspace

## Expected behavior
Maybe you have an idea for the reason, why it is not working on alfahosting webspace.

## Screenshots
![16-12-2023_15-48-35](https://github.com/contao-themes-net/mate-theme-bundle/assets/86398696/4260cc33-45ab-4d9e-85f5-3a05b043f0f1)

## Environment
Provider Alfahosting, PHP 8.2, MySQL 5.7, Contao 5.27, Mate 3.2.5

**Comment by acht11** [comment]
I has to do with "Bildformat konvertieren" 
When I disable all converters to WEBP, than it works.
![16-12-2023_16-17-07](https://github.com/contao-themes-net/mate-theme-bundle/assets/86398696/affb63f6-1638-4d9f-898a-ae640b3ec45d)

**Comment by MDevster** [comment]
Hallo @acht11 vielleicht kann dir der Alfahosting Support weiterhelfen, falls du webp einsetzen willst.

Vielleicht interessant für dich -> Zusätzliche Einstellungen für Alfahosting in der [.htaccess für Contao](https://pdir.de/news/die-perfekte-htaccess-datei-fuer-contao.html#alfahosting)

**Comment by acht11** [comment]
Hallo Mathias,

 

vielen Danke für die Info.

 

Grüße

 

Josef

 

 

Von: Mathias Arzberger ***@***.***> 
Gesendet: Montag, 18. Dezember 2023 09:54
An: contao-themes-net/mate-theme-bundle ***@***.***>
Cc: acht11 ***@***.***>; Mention ***@***.***>
Betreff: Re: [contao-themes-net/mate-theme-bundle] no picture when is installed on Alfahostings webspace (Issue #178)

 

Hallo @acht11 <https://github.com/acht11>  vielleicht kann dir der Alfahosting Support weiterhelfen, falls du webp einsetzen willst.

Vielleicht interessant für dich -> Zusätzliche Einstellungen für Alfahosting in der .htaccess für Contao <https://pdir.de/news/die-perfekte-htaccess-datei-fuer-contao.html#alfahosting>
