### ISSUE TITLE
Contao 5.2, custom.css wird ignoriert

### ISSUE THREAD

**Issue by samazaphikel** [contao-themes-net/mate-theme-bundle#179]
Hi,

ich habe leider einen konflikt mit einer anderen CSS, die ich über die amte cusom.css beheben wollte.

Sprich, ich wollte diesen part:
```
.container .row,.sectionTop .inside .row,.sectionTop .inside .mod_newslist,.sectionTop .inside .mod_eventlist,.sectionTop .inside .mod_newsarchive,.sectionTop .inside .left-col #container,.left-col .sectionTop .inside #container,.sectionTop .inside .right-col #container,.right-col .sectionTop .inside #container,.sectionTop .inside .left-right-col #container,.left-right-col .sectionTop .inside #container,#header .nav-wrapper .row,#header .nav-wrapper .mod_newslist,#header .nav-wrapper .mod_eventlist,#header .nav-wrapper .mod_newsarchive,#header .nav-wrapper .left-col #container,.left-col #header .nav-wrapper #container,#header .nav-wrapper .right-col #container,.right-col #header .nav-wrapper #container,#header .nav-wrapper .left-right-col #container,.left-right-col #header .nav-wrapper #container,.container .mod_newslist,.container .mod_eventlist,.container .mod_newsarchive,.container .left-col #container,.left-col .container #container,.container .right-col #container,.right-col .container #container,.container .left-right-col #container,.left-right-col .container #container {
    margin-left: -.75rem;
    margin-right: -.75rem;
    display: -webkit-flex;
    display: -ms-flex;
    display: flex;
    //-webkit-flex-wrap: wrap;
    //-ms-flex-wrap: wrap;
    //flex-wrap: wrap;
    clear: left
}

```
das auskommentierte entfernen und habe diesen Block in die custom.css geladen. Nur leider wird das komplett ignoriert. Ich bin davon ausgegangen, dass wenn ich das in die cusom.css lade das ich somit die "alten" Einstellungen überschreiben kann. In der chrome Entwicklerkonsole kann ich auch sehen, dass die custom.css geladen wurde. 

*caches sind geleert worden

Wie kann ich das nun auf dem richtigen Weg überschreiben? Bzw. die auskommentierten Bereiche entfernen?

**Comment by seibtph** [comment]
Ich weiß nicht genau was du vorhast, aber du kannst flex-wrap einfach auf einen anderen Wert setzen:

z. B.
```
.container.row {
  flex-wrap: inherit;
}
```

Damit passen sich die Inhaltselemente mobil aber nicht mehr richtig an. Wäre also nicht unbedingt empfehlenswert.

Das Auskommentieren bringt nichts, damit überschreibst du die Angaben nicht. Die Zeilen werden dann einfach ignoriert.

**Comment by samazaphikel** [comment]
Ändert aber dennoch leider nichts daran, wenn ich 
```
.container.row {
  flex-wrap: inherit;
}
```
in die custom.css eintrage und den cache leere, dass diese auch angewandt wird. Geladen ist die custom.css, wird aber nicht beachtet. Sprich, flex-wrap: inherit; ist über den Chrome Entwicklermodus sichtbar, aber keine Änderung

**Comment by seibtph** [comment]
Hättest du einen Link zu deiner Seite und was genau willst du denn erreichen?

**Comment by samazaphikel** [comment]
Habe erstmal alles wieder Rückgängig gemacht.

Ich möchte so wie in der Mate Demo, 2 Textfelder nebeneinander anzeigen lassen. Aber egal was ich tue, die bleiben untereinander.

Wie in der Demo habe ich diese beiden Textfeld zwischen Contao Themes (Inhaltscontainer Anfang) und Contao Themes (Inhaltscontainer Ende) plaziert.
Aber wie gesagt, diese bleiben untereinander.

Finde auch in den Theme Einstellung nichts was ich sonst noch einstellen könnte.


* Caches leeren, und Browser Cookies, sind gelleert

**Comment by seibtph** [comment]
Der Inhaltscontainer benötigt die Klasse `row` und den Textelementen darin gibst du z. B. die Klassen `col s12 m6`. Die Klassen bei den Textelementen kannst du unter Erweiterte CSS-Klassen auswählen.

![image](https://github.com/contao-themes-net/mate-theme-bundle/assets/17127525/095d763b-7aec-4a08-919e-d46954cda18e)

Ist das bei dir so eingestellt? 

Hast du sonst mal einen Link zu deiner Seite, falls das nicht helfen sollte? Die Angabe flex-wrap: inherit kannst du dir auf jeden Fall sparen.

**Comment by samazaphikel** [comment]
Wo genau finde ich diese Einstellungen aus dem Bild?
Ich kann die nirgends finden. 

Bei Erweiterte CSS-Klassen sieht das bei mir so aus.
![IMG_9857](https://github.com/contao-themes-net/mate-theme-bundle/assets/35742942/9c32bbdd-a15c-413e-abf1-b8affb97c0d4)

die .col Attribute sind garnicht im dropdown vorhanden, ebenso die Spaltenbreite ist nicht aufgeführt. Ich kann hier nur .span und .offset einstellen.

Offtopic,
ich weiß nicht ob das evtl zusammenhängt….
In einer subdomain habe ich mir frisches Container 5.2 installiert mit dem mate Theme, sonst keine Erweiterungen, das frontend ist nicht sichtbar. 

Die links schicke ich gleich per Mail.

**Comment by seibtph** [comment]
Schau mal in den Einstellungen der Root-Seite, da sollte unter Erweiterte CSS-Einstellungen das materialize Klassen-Set ausgewählt sein. Vermutlich ist da bei dir etwas anderes ausgewählt.

![image](https://github.com/contao-themes-net/mate-theme-bundle/assets/17127525/55b2c22a-6279-4af1-80ef-60655e81f403)
