### ISSUE TITLE
Contao 5.3 supported?

### ISSUE THREAD

**Issue by fenepedia** [contao-themes-net/mate-theme-bundle#182]
I have tried to install the mate-theme under Contao 5.3.
So far the installation has worked.

When calling the frontend the following error appears in the log.
`request.CRITICAL: Uncaught PHP Exception Twig\Error\SyntaxError: "An exception has been thrown during the compilation of a template ("The template "content_element/_base" could not be found in the template hierarchy.") in "@Contao/content_element/text.html.twig"." at Environment.php line 523 {"exception":"[object] (Twig\\Error\\SyntaxError(code: 0): An exception has been thrown during the compilation of a template (\"The template \"content_element/_base\" could not be found in the template hierarchy.\") in \"@Contao/content_element/text.html.twig\". at /www/cto5/vendor/twig/twig/src/Environment.php:523)\n[previous exception] [object] (LogicException(code: 0): The template \"content_element/_base\" could not be found in the template hierarchy. at /www/cto5/vendor/contao/core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php:303)"}`

Has the theme already been released for Contao 5.3?

**Comment by seibtph** [comment]
Can you please clear the cache?

**Comment by seibtph** [comment]
This is a known contao problem. You should be able to fix it by clearing the cache.

Slack Thread: https://contao.slack.com/archives/CK4J0KNDB/p1708334207983099

**Comment by fenepedia** [comment]
Thank you. This worked. I will close the ticket.
