### ISSUE TITLE
Click auf Suche aus dem Header (Lupe)  stösst Laden der Startseite an / Click on header search icon starts reload of start page

### ISSUE THREAD

**Issue by TPSKrudern** [contao-themes-net/mate-theme-bundle#183]
Ein Click auf die Suchfunktion im Header (Lupe) lässt das Overlay active werden.  Allerdings wird direkt danach die Startseite aufgerufen (Link auf '/#'). Auf der Demo-Seite funktioniert es nur auf der Startseite selber, d.h. das Overlay bleibt bestehen und es findet kein Neuladen/Weiterleiten statt. Auf Unterseiten z.B. https://mate.pdir.de/inhaltselemente/akkordion.html wird das fehlerhafte Verhalten ausgelöst, keine Chance die Suche auf diese Weise zu nutzen  Getestet im aktuellen Chrome und FF, sowohl Desktop wie auch mobile. 

A click on the search icon in header section gives active class to the right overlay. But after that the link '#' works and the start page is loading. On the mate demo-page only the behaviour on the start page is okay, i.e. the overlay is shown and there is no reload/forwarding.  On other pages e.g. https://mate.pdir.de/inhaltselemente/akkordion.html the wrong behaviour is shown, no chance to use the search that way. Tested with actuall chrome and firefox, desktop and mobile.

seen on MATE 3.3.0 and actual version

**Comment by seibtph** [comment]
Fixed in version 3.3.2
