### ISSUE TITLE
Multi-Domain Setup in Contao 5

### ISSUE THREAD

**Issue by mrflory** [contao-themes-net/mate-theme-bundle#184]
## Bug description
Multi-domain configuration as described in [documentation](https://pdir.de/docs/de/contao/themes/mate/customization/multiple_domains/) doesn't work in Contao 5.

## Solution
Path `../../../../public/bundles/matetheme/sass/` needs to be replaced with `../../../../vendor/contao-themes-net/mate-theme-bundle/public/sass/`

**Comment by seibtph** [comment]
Thank you. We will update our documentation.

This also works:

`../../../../public/bundles/contaothemesnetmatetheme/sass/`
