### ISSUE TITLE
Class not found Error bei Anhängen in News

### ISSUE THREAD

**Issue by mlirsch** [contao-themes-net/mate-theme-bundle#190]
## Bug description
Enthält ein News-Beitrag Anlagen, wird ein Class not found Error vom Template "news_mate_full" ausgegeben.
`request.CRITICAL: Uncaught PHP Exception Error: "Class "Image" not found" at news_mate_full.html5 line 22 {"exception":"[object] (Error(code: 0): Class \"Image\" not found at /var/www/html/mate/vendor/contao-themes-net/mate-theme-bundle/contao/templates/modules/mate/news_mate_full.html5:22)"} {"request_uri":"http://mate.local/news-details/mitten-im-elbtal-gelegen","request_method":"GET"}`

## Steps to reproduce
News-Beitrag bearbeiten und eine oder mehrere Anlagen hinzufügen.
News-Detailansicht im Frontend öffnen.

## Environment
PHP version 8.1
Contao Version 5.3.13
Mate Theme Bundle 3.4.1

**Comment by seibtph** [comment]
Fixed in version 3.4.2
