### ISSUE TITLE
Fehler beim Import der DB

### ISSUE THREAD

**Issue by felixpfeiffer** [contao-themes-net/mate-theme-bundle#2]
Hallo, wenn ich, wie in der Dokumentation beschrieben die Datenbank per phpMyAdmin versuche zu importieren, bekomme ich folgenden Fehler:

Fehler
SQL-Befehl:

-- -- Daten für Tabelle `tl_files` -- INSERT INTO `tl_files` (`id`, `pid`, `tstamp`, `uuid`, `type`, `path`, `extension`, `hash`, `found`, `name`, `importantPartX`, `importantPartY`, `importantPartWidth`, `importantPartHeight`, `meta`) VALUES (28, '�4�� �\0@�\\"�A', 1517219079, '�ʐ��[�\0@�\\"�A', 'file', 'files/mate/img/meissen/frauenkirche-meissen.jpg', 'jpg', 'd4a41178074b36f30958dd67eec7e387', '1', 'frauenkirche-meissen.jpg', 112, 236, 1088, 950, 0x613a313a7b733a323a226465223b613a343a7b733a353a227469746c65223b733a303a22223b733a333a22616c74223b733a303a22223b733a343a226c696e6b223b733a303a22223b733a373a2263617074696f6e223b733a303a22223b7d7d), (26, '�4�� �\0@�\\"�A', 1516371285, '����#�\0@�\\"�A', 'folder', 'files/mate/sass', '', 'e61d8bfcce6076128798be180e1ed03e', '1', 'sass', 0, 0, 0, 0, NULL), (25, '�4�� �\0@�\\"�A', 1516370378, '�H''� �\0@�\\"�A', 'file', 'files/mate/img/mate_logo_white.png', 'pn[...]

MySQL meldet: Dokumentation

#1062 - Duplicate entry '\xEF\xBF\xBD{\xEF\xBF\xBD\xEF\xBF\xBD\xEF\xBF\xBDv\x11\xEF' for key 'uuid' 

Natürlich habe ich vorher alle notwendigen Tabellen geleert.

MySQL ist in Version 5.6.38 und php in Version 7.1.12 und Contao ist 4.4.18

Eine kurze Rückmeldung wäre super.

Felix

**Comment by seibtph** [comment]
Der Fehler sollte nun in der Version 1.0.34 behoben sein. Die SQL Datei habe ich angepasst, scheint ein Codierungsproblem gewesen zu sein.
