### ISSUE TITLE
Contao 4.7 - Import funktioniert nicht

### ISSUE THREAD

**Issue by daniel-nemeth** [contao-themes-net/mate-theme-bundle#20]
Hallo!
Beim Versuch das Theme bei Contao 4.7 zu importieren kommt die folgende Meldung im Install-Tool:
_Der Import konnte nicht abgeschlossen werden! Ist die Datenbank aktuell und die Template-Datei kompatibel mit Ihrer Contao-Version?_

**Comment by seibtph** [comment]
Hallo,

wir haben es nochmal mit der 4.7.0 und 4.7.1 getestet und da hat der Import funktioniert. Die Datenbank sollte aber leer sein (also nur die Tabellen angelegt sein ohne Inhalt), ansonsten kann es zu diesem Fehler kommen.

**Comment by oknirw** [comment]
bei mir geht es mit contao 4.4.36 auch nicht...

**Comment by MDevster** [comment]
@seibtph Please test a blank Contao 4.4.36.

**Comment by seibtph** [comment]
Getestet mit der 4.4.40 und der Import hat funktioniert. Eventuell nochmal die alten SQL-Files im templates-Ordner löschen und über "Theme-Dateien synchronisieren" neu kopieren.
