### ISSUE TITLE
Configuration in parameters.yml

### ISSUE THREAD

**Issue by ZWonGit** [contao-themes-net/mate-theme-bundle#21]
I added the values below into app/config/parameters.yml while skipping the web/ dir. Does this still working with contao 4.6 / 4.7? It seems it has no effects.
```
parameters:
    mate_theme.assets.custom_scss: 'files/my/path/_custom.scss'
    mate_theme.assets.custom_colors : 'files/my/path/_custom_colors.scss'
    mate_theme.assets.custom_variables : 'files/my/path/_custom_variables.scss'
```

**Comment by MDevster** [comment]
Sorry, the feature is documented, but not yet implemented in the MATE theme bundle.
We have not yet found a secure way to adjust the paths in the materialize.scss. We need it update safe.
We will review the implementation in one of the next releases.

For now you can edit this file:
https://github.com/contao-themes-net/mate-theme-bundle/blob/master/src/Resources/public/sass/materialize.scss
