### ISSUE TITLE
materialize.json

### ISSUE THREAD

**Issue by ynrog** [contao-themes-net/mate-theme-bundle#22]
In der Installationanleitung heißt es: "Unter Erweiterte CSS-Einstellungen müssen Sie noch das Klassen-Set materialize.json auswählen". Unter "System / Einstellungen" gibt es bei mir den Punkt "Erweiterte CSS-Einstellungen" nicht. Wo sonst kann man das Klassen-Set einstellen?

**Comment by MDevster** [comment]
Bitte prüfe ob das Bundle contao-dd/advanced-classes-bundle ordnungsgemäß installiert wurde. Sollte dies der Fall sein benötigen wir weitere Informationen zur Installation. (PHP Version, Contao Version, Theme Version usw.)

**Comment by ynrog** [comment]
Das advanced-classes-bundle ist installiert. Habe alles noch mal aktualisiert, aber keine Änderung. Php-Version ist 7.3.2, Contao = 4.7.1, Mate = 1.7.5. Im install-Tool läßt sich das Mate-Demo-Template nicht problemlos importieren. Wenn der Haken bei "Tabellen nicht leeren" aktiviert ist, kommt eine Fehlermeldung "Der Import konnte nicht abgeschlossen werden!" Wenn der Haken bei "Tabellen nicht leeren" nicht gesetzt ist, scheint das Template importiert zu werden. Im Backend erscheint es aber nicht unter "Layout/Templates", nur  unter "Themes".

**Comment by effeff19** [comment]
Ich habe das gleiche Problem. (contao 4.7.2)
Das Theme funktionert ohne Slider. Liegt dies an den erweiterten css-Einstellungen?

**Comment by MDevster** [comment]
Das Problem sollte nun mit Version 1.0.1 des Advanced Classes Bundle behoben sein.

**Comment by effeff19** [comment]
Klappt- herzlichen Dank! 
Der Slider funktioniert immer noch nicht.
Im Backend erhalte ich folgenden Hinweis auf der Seite 
Artikel › Content Slider › Inhaltselemente › Inhaltselement ID 489 bearbeiten
Hinweis: Das js_slider-Template muss im Seitenlayout eingebunden sein.
Was habe ich da vergessen?

**Comment by seibtph** [comment]
@effeff19 Den Fehler beim Content Slider haben wir nun in der Version 1.7.6 behoben.
