### ISSUE TITLE
slider not working under new contao

### ISSUE THREAD

**Issue by AdminBK85** [contao-themes-net/mate-theme-bundle#23]
Hi there, 
I'm using your theme mate - after updated to the latest contao version the slider isn't displayed anymore. Are you aware of that issue - any suggestions?

www.seehausen-fussball.de is the page. 

Thanks in advance. 

Kind regards,
Bea

**Comment by MDevster** [comment]
Problem is obviously solved. If there are any problems please comment on the ticket again.
