### ISSUE TITLE
Responsive menu on iPhone and Safari not working

### ISSUE THREAD

**Issue by rwaelty** [contao-themes-net/mate-theme-bundle#24]
## Bug description

To try out I've installed the MATE Theme 1.8.2 on Contao 4.4.40. But the responsive Nav Menu seems not to work on an iPhone 10 with ios 12.3.1 and Safari. On Chrom it's ok. On the iPad and on the Mac it works  correctly (responsive and normal). PHP on the CYON Server 7.2.18. It seems to be a problem with Safari.
See als the 3 screen shots, 1+2 iPad, 3 iPhone with Safari. 
Regards Rolf

![IMG_0499](https://user-images.githubusercontent.com/10787922/59502127-52b34200-8e9d-11e9-81c1-f53998545ca4.PNG)
![IMG_0500](https://user-images.githubusercontent.com/10787922/59502129-52b34200-8e9d-11e9-8be0-6e520fe91083.PNG)
![IMG_1053](https://user-images.githubusercontent.com/10787922/59502132-534bd880-8e9d-11e9-9053-d8519e2486d7.JPG)

**Comment by MDevster** [comment]
@rwaelty The bug should already be fixed in the latest version of the theme.
