### ISSUE TITLE
Dropdown-Menue auf Tablets fünktioniert nicht

### ISSUE THREAD

**Issue by ManuelaMe** [contao-themes-net/mate-theme-bundle#25]
Auf dem Ipad klappt die Dropdown Navigation nicht auf, weder bei der Mate-Demo noch bei unsererm Projekt. Manchmal sieht man im Chrome beim Test ganz kurz (2sec.) das Menü aufklappen. Es klappt aber sofort wieder zu.

[image](https://user-images.githubusercontent.com/24274084/60163098-25e71f00-97fb-11e9-87a1-296366c93252.png)

Wir verwenden bei unserem Projekt Contao 4.4.36 mit der Mate-Version 1.8.2

**Comment by seibtph** [comment]
Der Fehler ist in der Version 2.1.0 behoben. In der Demo funktioniert es auch wieder.
