### ISSUE TITLE
Improve Mobile Handling

### ISSUE THREAD

**Issue by mr2017x** [contao-themes-net/mate-theme-bundle#26]
Good Morning,

i like your Mate Theme and fill it up with Details and information, works mostly like a charm, but now i saw, that the "header", especially on first page is broken on long mobile display. Therefore i want to ask if you can improve this to extend this to the bottom of the first view?

To clarify i mean the Element with

"
WISSENSWERTES
Porzellan- und Weinstadt Meißen
International berühmt ist die Stadt Meißen für die Herstellung des Meißner Porzellans, das als erstes europäisches Porzellan seit 1708 hergestellt wird.

MEHR DAZU"

Thanks in advance

**Comment by seibtph** [comment]
Can you post a screenshot of this bug?
