### ISSUE TITLE
Update auf 2.0 

### ISSUE THREAD

**Issue by Peresics** [contao-themes-net/mate-theme-bundle#27]
Hi,

momentan ist auf meiner Seite die Version 1.9.1 installiert. Im Manager habe ich schon mehrfach das Theme aktualisiert, aber es bleibt bei dieser Version. Muss ich eine bestimmte Einstellung vornehmen um auf die 2.0 Version zuzugreifen?

**Comment by seibtph** [comment]
Wenn du im Contao Manager bei der Version ^2.2 einträgst sollte er die aktuelle Version installieren. Hast du das gemacht?

**Comment by Peresics** [comment]
Hi,

sorry für die späte Antwort. Hat funktioniert! 
Danke
