### ISSUE TITLE
Demobilder werden nicht angezeigt

### ISSUE THREAD

**Issue by uwegrothe33** [contao-themes-net/mate-theme-bundle#29]
Ich habe MATE Version 2.2.7 (lizensiert) installiert auf CONTAO Version 4.4.12. Funktioniert alles bis auf das die Demobilder nicht angezeigt werden. In der Dokumentation finde ich dazu keine Angabe. 

Jemand eine Idee was ich übersehen habe?

**Comment by seibtph** [comment]
Haben Sie die Installation genauso wie in der Dokumentation beschrieben durchgeführt und auch am Ende die Symlinks neu aufgebaut? Ich habe gerade erst die Installation getestet und das klappte alles.
