### ISSUE TITLE
MATE THEME Menüpunkt erscheint nicht im Backend

### ISSUE THREAD

**Issue by ManuelRitter** [contao-themes-net/mate-theme-bundle#3]
Hi,

ich habe eine frisches Contao 4.4  und das Mate Theme Bundle mittels Contao Manager installiert und die Datenbank über das Install Tool aktualisiert. Das hat auch alles ohne Fehlermeldungen funktioneirt, jedoch erscheint im Backend der Menüpunkt MATE THEME nicht.

Installiert habe ich das ganze auf einem Debian Server mit Apache2 und PHP 7.0.27-0+deb9u1 

Gibt es eine möglichkeit das Theme manuell zu installieren oder muss ich noch etwas tun um den Menüpunkt MATE THEME zu bekommen?

Gruß
Manuel

**Comment by MDevster** [comment]
Hallo Manuel,
konntest du das Problem lösen?

**Comment by newuser134** [comment]
Hallo
Ich habe das selbe Problem. Bei mir erscheint der Menupunkt im Bakcend auch nicht... Gibt es irgendwo bereits einen Lösungsweg zum Nachlesen?

**Comment by MDevster** [comment]
> Hallo
> Ich habe das selbe Problem. Bei mir erscheint der Menupunkt im Bakcend auch nicht... Gibt es irgendwo bereits einen Lösungsweg zum Nachlesen?

Hallo newuser134, kannst du mir bitte noch folgende Fragen beantworten?
Welche Version des Themes hast du installiert?
Welche Contao Version nutzt du?
Welche PHP Version wird verwendet?

**Comment by newuser134** [comment]
Hallo 

Hier meine Versionen: 

Version des Themes: 1.0.7
Contao Version: 4.4.29 (API-Version 0)
PHP Version: 7.0.32


Am 04.12.2018 um 08:03 schrieb Mathias Arzberger <notifications@github.com>:

Hallo
Ich habe das selbe Problem. Bei mir erscheint der Menupunkt im Bakcend auch nicht... Gibt es irgendwo bereits einen Lösungsweg zum Nachlesen?

Hallo newuser134, kannst du mir bitte noch folgende Fragen beantworten?
Welche Version des Themes hast du installiert?
Welche Contao Version nutzt du?
Welche PHP Version wird verwendet?

**Comment by MDevster** [comment]
Wir schauen uns das Problem heute genauer an.

**Comment by MDevster** [comment]
Habt Ihr die Möglichkeit auf PHP 7.1 oder höher zu wechseln? Dann könntet Ihr auch die aktuellste Version des Themes nutzen.

**Comment by newuser134** [comment]
Guten Morgen
Habe jetzt eine komplett neue Installation gemacht. PHP 7.2. Die Installation des Contao Managers verlief fehlerfrei. Soweit alles gut. Wenn ich jetzt versuche, das Mate Theme zu installieren, erscheint nachfolgende Fehlermeldung und die Installation wird abgebrochen. Die php-Einstellungen habe ich unten kopiert. 

News für Contaocontao/news-bundle
Console task terminated!
The background task has stopped unexpectedly. Please check the console protocol.

$ /opt/php72/bin/php '-q' '/home/httpd/vhosts/ara-worblental19.ch/httpdocs/web/contao-manager.phar.php' 'composer' 'require' 'contao-themes-net/mate-theme-bundle' '--no-suggest' '--no-update' '--no-scripts' '--prefer-stable' '--sort-packages' '--no-ansi' '--no-interaction' 2>&1 Using version ^1.5 for contao-themes-net/mate-theme-bundle /home/httpd/vhosts/ara-worblental19.ch/httpdocs/composer.json has been updated # Process terminated with exit code 0 # Result: OK $ /opt/php72/bin/php '-q' '/home/httpd/vhosts/ara-worblental19.ch/httpdocs/web/contao-manager.phar.php' 'composer' 'update' 'contao-themes-net/mate-theme-bundle' '--with-dependencies' '--prefer-dist' '--no-dev' '--no-progress' '--no-suggest' '--no-ansi' '--no-interaction' '--optimize-autoloader' 2>&1 Loading composer repositories with package information Updating dependencies Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors. # Process terminated with exit code 255 # Result: Unknown error --- ### The background task has stopped unexpectedly. ###





Am 04.12.2018 um 09:20 schrieb Mathias Arzberger <notifications@github.com>:

Habt Ihr die Möglichkeit auf PHP 7.1 oder höher zu wechseln? Dann könntet Ihr auch die aktuellste Version des Themes nutzen.

**Comment by MDevster** [comment]
@newuser134 Dein Problem ist das Memory Limit siehe
> https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

Hast du die Installation mal mit aktiver Composer Cloud probiert?
