### ISSUE TITLE
module newslist - "blank" funktioniert nicht trotz angehakt

### ISSUE THREAD

**Issue by designu** [contao-themes-net/mate-theme-bundle#30]
<a class="more" href="https://www.???.ch">+</a>

"blank" is missing

**Comment by seibtph** [comment]
Den Fehler kann ich in der aktuellen Version nicht nachvollziehen. Wenn ich bei Weiterleitungsziel eine externe URL (mit http) angebe und "In einem neuen Fenster öffnen" anhake, funktioniert die Weiterleitung auch in einem neuen Tab.
