### ISSUE TITLE
Drop Down Issues with Internet Explorer 11+

### ISSUE THREAD

**Issue by JoschuaXner** [contao-themes-net/mate-theme-bundle#31]
## Bug description
Using the drop downs in Internet Explorer results in 2 issues:
1. Issue - Background of a dropdown with to much elements is cropped
2. Issue - Clicking on a subfield of a drop down results in a 404 because the url is assembled incorrectly

## Steps to reproduce
1. Issue 
   1.1. Go to https://mate.pdir.de/
   1.2. Hover over the drop down entry "Elemente"

2. Issue
   2.1. Go to https://mate.pdir.de/
   2.2. Hover over the drop down entry "Layouts" 
   2.3. Click on "Layout mit linker Spalte"
   2.4. Hover over the drop down entry "Elemente"
   2.5. Click on "Mate-Elemente"

## Expected behavior
1. Issue - Drop down background surrounds all of the elements

2. Issue - URL gets assembled correctly so no 404 pops up

## Screenshots
1. Issue
![1 Issue](https://user-images.githubusercontent.com/18641110/69350893-ab6fdd80-0c7a-11ea-96f3-69ce0a87578d.png)

2. Issue
![2 Issue](https://user-images.githubusercontent.com/18641110/69350945-c80c1580-0c7a-11ea-948e-844873a89f73.png)

## Environment
Internet Explorer Version: 11+

**Comment by JoschuaXner** [comment]
Do you have an ETA for a fix or a solution where i can solve this locally?

**Comment by seibtph** [comment]
Both problems are fixed in version 2.3.2.

**Comment by JoschuaXner** [comment]
i updated to version 2.3.2. and the 2. Issue is fixed.
The 1. Issue still exists, do I have to make further changes than just updating the version?
