### ISSUE TITLE
navigation menu with external links broken

### ISSUE THREAD

**Issue by michael-j-r** [contao-themes-net/mate-theme-bundle#33]
## Bug description

Updating Contao to 4.8.7 and Mate-theme to 2.3.4  created and odd behavior resolving external links from the navigation menu.
## Steps to reproduce

Create at the top-level menu an entry with page type external link (externe weiterleitung) and let it point to  eg.      http://google.de
 This unfotunately wil create a link pointing to 

https://www.mydomain.de/http://google.de

which can not be resolved. 

The behavior changes with the width of the browser window. If the screen is wide and the
menue is displayed as menu bar, then ist FAILS.
If the screen is small and the mobile navigation with main-pulldown menu appears,
then the link is working.

The debug output in contao shows an unexpected leading slash at the external URL which might
be interpreted as directory and then will be replaced by the domains URL. leading
to   
https://www.mydomain.de/http://google.de
instead of
http://google.de

Might be related to 
https://github.com/contao-themes-net/mate-theme-bundle/commit/3096c29d32516aff27352af6563b95ed244b164e

## Environment

Contao  4.8.7
Mate 2.3.4
PHP 7.3
Browser: Chrome  or Firefox

**Comment by xchs** [comment]
> The behavior changes with the width of the browser window. If the screen is wide and the
> menue is displayed as menu bar, then ist FAILS.
> If the screen is small and the mobile navigation with main-pulldown menu appears,
> then the link is working.

This is – of course – due the fact that the changes in https://github.com/contao-themes-net/mate-theme-bundle/commit/3096c29d32516aff27352af6563b95ed244b164e were only made for the "desktop" templates and not for the `nav_mate_mobile.html5` template as well. So basically it has nothing to do with the browser width.

**Comment by erikp152** [comment]
I can also reproduce this issue with Contao 4.4* and a linked external Page in second level in navigation.

**Comment by michael-j-r** [comment]
Ok, thanks for the clarification.

I downgraded the mate-them to version  2.2.10 and cleared all Contao caches.
Now it works again as expected.
Is the any recent version which you can recomment, for sure  I can play with
different revisions for my self as well.

Thanks and regards,
Michael

**Comment by michael-j-r** [comment]
The template    nav_mate_left.html5   in the mate-theme  shows a similar issue.

**Comment by xchs** [comment]
Yes, it concerns all the templates that were modified in https://github.com/contao-themes-net/mate-theme-bundle/commit/3096c29d32516aff27352af6563b95ed244b164e.
Only the `nav_mate_mobile.html5` template left untouched since you don't usually have IE running on mobile devices.

**Comment by seibtph** [comment]
I have fixed this problem in MATE theme version 2.3.5.
