### ISSUE TITLE
Mate calendar default/mini

### ISSUE THREAD

**Issue by quaxim01n** [contao-themes-net/mate-theme-bundle#34]
calendar DEFAULT (big one): shows marked dates on PC, clicks lead perfectly to event detail (with further forwardings and booking info), BUT it cannot be seen on mobile phone (shows only the months/headline, no calendar table, no option to get to booking and forward)
calendar MINI: shows up on phone and PC with marked dates/days, but clicks do not open the event details. (Also not on the demo site as I found out)
In both Modules I checked same settings and many trials. Why does MINI not go to details or why can I then not adjust the bigger DEFAUKT for the phone? Could I?
I do not find much options in the "variables" CSS or such...

**Comment by seibtph** [comment]
In the default calendar the events will also be shown on mobile phone (fixed in MATE theme version 2.3.4).

![calendar_mobile](https://user-images.githubusercontent.com/17127525/72066824-d6bd9300-32e1-11ea-840f-2e8274051eac.png)

And the mini calendar shows all events on the date which you clicked.

**Comment by quaxim01n** [comment]
Festnetz: +41(0)715352460
Mobil: +41(0)762285537
Ganzheitliche Massageü

Gesendet von unterwegs.
