### ISSUE TITLE
Ändern der Standartfarben durch auskommentieren in _custom_variables.scss geht nicht.

### ISSUE THREAD

**Issue by FastFussel** [contao-themes-net/mate-theme-bundle#35]
Ich habe ein Contao 4.8.7 unter xampp gestern installiert und darauf dann das Mate Team Bundle in der Version 2.3.4 ohne Probleme installiert. 
Bei der in der Installationsanleitung beschriebenen "Auskommentierung"des Farbschemas
in "files/mate/sass/_custom_variables.scss" @import 'mate_color_schemes/mate_blue_colors'; passiert aber nichts.
Also die blauen Grundfarben erscheinen nicht wie in der Installationsanleitung beschrieben.
Was kann ich tun ?

**Comment by seibtph** [comment]
Hast du auch den Cache geleert (Skriptcache leeren und/oder die Seite mit Strg + F5 neuladen)?

Wenn das nicht hilft, werde ich mal eine lokale Testumgebung aufsetzen und es dort testen. Bisher haben wir es lokal noch nicht getestet.

**Comment by mstudio-dev** [comment]
Gleiches Problem unter Contao 4.4.46 auf einem Netcup-Webhosting-Paket. Die Installationsfarbe ist hier grün. Ich wollte _custom_colors.scss anpassen: 
`/* ============================= */
/*        Colour Schemes         */
/* ============================= */

@import 'mate_color_schemes/mate_dark_colors';
@import 'mate_color_schemes/mate_blue_colors';
@import 'mate_color_schemes/mate_yellow_colors';


/* ============================= */
/*     MATE Theme Variables      */
/* ============================= */

/* Colors */
$mateColor1: #ffcdd2;
$mateColor2: #b71c1c;
//$mateColor3: #476a30;
//$mateColor4: #58774e;
//$mateColor6: #abbdb1;`

Hab ich was vergessen?

**Comment by seibtph** [comment]
Welche MATE Theme Version wird genutzt? Evtl. mal zur neuesten Version 2.6.0 updaten und schauen ob es dann wieder geht.

**Comment by seibtph** [comment]
Der Fehler, dass unter einer lokalen Umgebung unter Windows die Variablen nicht anzupassen gehen, haben wir nun in der MATE Theme Version 2.7.1 gefixt.

Wenn die fe_page_mate.html5 angepasst wurde, müsste folgende Zeile ...

```
$combiner->add('bundles/matetheme/sass/mate.scss');
```

durch folgende Zeilen ersetzt werden:

```
if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
    $combiner->add('bundles/matetheme/sass/mate_win.scss');
} else {
    $combiner->add('bundles/matetheme/sass/mate.scss');
}
```
