### ISSUE TITLE
 Frontend   Fehler bei Einstellung Navigation ohne Dropdown

### ISSUE THREAD

**Issue by rsch2020** [contao-themes-net/mate-theme-bundle#36]
## Bug description
Im MATE Theme Version 2.3.5 kommt es zu einem Fehler bei
Module Setup Themes › mate › Front end module Navigation / Hauptnavigation [Navbar]
Navigation without Dropdown, align right
## Steps to reproduce
Setup "Navigation without Dropdown, align right" führt zu  Contao Frontend Fehler
Es erfolgt dabei kein Log Eintrag in /var/logs. 
########################################################################
Fehler  durch  NavBarModule.php 
if ($this->mateNavbarType == 'type1')
        {
            $this->mateRootTpl = 'nav_mate_left';
            $this->mateMobileTpl = 'nav_mate_mobile';
            $this->mateDropdownTpl = '';
        }
Nach Eintrag von  $this->mateDropdownTplLvl3=''; ist der Fehler behoben.

if ($this->mateNavbarType == 'type1')
        {
            $this->mateRootTpl = 'nav_mate_left';
            $this->mateMobileTpl = 'nav_mate_mobile';
            $this->mateDropdownTpl = '';
            $this->mateDropdownTplLvl3 = '';
        }

## Environment
Linux SuSE Leap 15.1, PHP 7.2.5 , Contao Version 4.8.7

**Comment by seibtph** [comment]
fixed in version 2.4.1
