### ISSUE TITLE
Farbauswahl in CONTAO 4.8 funktioniert nicht

### ISSUE THREAD

**Issue by schlomogast** [contao-themes-net/mate-theme-bundle#38]
Ich habe ein bestehendes CONTAO 4.7 geupdatet auf 4.8.  Dabei ist leider die Farbauswahl auf der Strecke geblieben. Es geht nur noch grün. Das alte Import Blau wird übergangen in der _custom_colors.scss.

**Comment by seibtph** [comment]
fixed in version 1.9.2
