### ISSUE TITLE
kein Theme zu sehen

### ISSUE THREAD

**Issue by Andiamolino** [contao-themes-net/mate-theme-bundle#39]
## Bug description
Nach Mate-Installation ist kein Inhalt/Theme zu sehen.

## Steps to reproduce
Webhoster DM-Solutions (momentan php 7.2.25 + mysql-db)
Frisches leeres contao 4.4.46 aufgesetzt. Mate-theme per Contao Manager installiert. Schritte genau nach Anweisungen abgearbeitet. Keine Inhalte, DB ist ebenfalls nicht gefüllt. aber in Files sind die entsprechenden Daten/ordner kopiert/erstellt worden.

## ausgrenzungsversuch:
Diese Vorhergehensweise mehrmals wiederholt (alles vom Webserver gelöscht, unterschiedliche php-versionen , mehrere contao-versionen ab 4.0. minimal installation bzw. max-install.) immer mit dem selber Ergebniss.
danke schon mal.
A.

**Comment by seibtph** [comment]
Unter Contao 4.4.46 und der MATE Theme Version 2.4.0 konnte ich jetzt keine Probleme feststellen. In unserer Testumgebung wurde alles richtig importiert.

Wurde das MATE Theme Bundle richtig installiert, erscheint vielleicht ein Fehler beim Installieren der Pakete? Am besten nochmal auf Aktualisieren klicken, vielleicht wurde irgendetwas nicht korrekt installiert.

**Comment by Andiamolino** [comment]
Seit gestern läuft es. Es lag wohl an den Einstellungen von webserver. 

Es kamen auch keine Fehlermeldungen, habe dann versucht andere themes zu installieren, da war das gleiche problem. Also lag die Vermutung nahe, das der Server die Ursache dafür sein musste.

Ich habe alles gelöscht, den webaccount neu erstellen lassen. Nachdem alles neu eingerichtet wurde, klappte es tadellos. 
Danke für das theme, es gefällt mir gut.
