### ISSUE TITLE
SideNav will not get load after last update

### ISSUE THREAD

**Issue by mr2017x** [contao-themes-net/mate-theme-bundle#40]
Refused to apply style from 'https://xy/assets/css/components/sideNav' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

I think there is a global problem?

**Comment by seibtph** [comment]
Which MATE Theme version do you have? If you have installed the version 1.9.2 than you should update to version 1.9.3.
