### ISSUE TITLE
New Install of Mate 2.x Subpages throw 404

### ISSUE THREAD

**Issue by mr2017x** [contao-themes-net/mate-theme-bundle#41]
Good Evening,

i have a new installation of mate theme 2.0, when access pages like kontakt, even in combination with en or de /de/kontakt/ or /en/contact/ everything is ok.

But when trying to access layout - layout mit linker Spalte it redirects to
/layouts/layout-mit-linker-spalte/layout-mit-linker-spalte/layout-mit-linker-spalte/layout-mit-linker-spalte/ which throws a 404 error

what do i need to change? 

Configuration is based on nginx and debian

**Comment by seibtph** [comment]
You should enable folder URLs (Settings - Front end configuration). I think that's the problem.
