### ISSUE TITLE
Teaserbox / Sichtbarkeit

### ISSUE THREAD

**Issue by Peresics** [contao-themes-net/mate-theme-bundle#42]
Hi,

bei den Teaserboxen gibt es bei mit keine Möglichkeit die Veröffentlichung festzulegen (Anzeigen Ab / Anzeigen Bis). Ist das so gewollt oder funktioniert bei mir was nicht? Ich habe momentan die Version 2.4.1 installiert.

**Comment by seibtph** [comment]
Wir haben diese Felder in der Version 2.6.0 nun hinzugefügt.
