### ISSUE TITLE
Update Mate Theme von 2.3 auf 2.7

### ISSUE THREAD

**Issue by Clumsy88** [contao-themes-net/mate-theme-bundle#43]
Contao 4.9.1
www.worx.limbach-ww.de

Nach dem Update des Mate Themes von 2.4 (Installation von Herbst 2019) auf 2.7 kann die WebSite nicht mehr aufgerufen werden. Vor dem Update des Mate-Themes hab ich das Update auf Contao 4.9.1 laufen lassen. Danach lief die Seite ohne Probleme. Erst nach dem Mate-Theme Update auf 2.7 war die Seite nicht mehr abrufbar. 

 Im Frontend wird die Fehlermeldung...

> Bei der Ausführung des Skriptes ist ein Fehler aufgetreten. Irgendetwas funktioniert nicht richtig.
> Wie kann ich das Problem lösen?
> Öffnen Sie die aktuelle Log-Datei im Ordner var/logs und suchen Sie die zugehörige Fehlermeldung (normalerweise die letzte).

ausgewiesen. 

In den LOG Dateien finde ich dann nur folgende Fehlermeldung...

2020-03-07 11:30:11 | Error | 89.110.145.28 | 500 | GET /preview.php/ HTTP/1.0

Im DEBUG-Mode findet sich dann folgende Fehlermeldung...

`../../../../../../../files/mate/sass/_custom_colors` file not found for @import: /var/www/vhosts/limbach-ww.de/contao4-cms2/web/bundles/matetheme/sass/materialize.scss on line 5, at column 1

Besagte Datei "_custom_colors" befindet sich aber genau dort im genannten Zielverzeichnis.  Die Variablen in der Datei sind angepasst für "@import 'mate_color_schemes/mate_blue_colors". Bis zum Update lief alles problemlos. 

Was kann ich tun?

**Comment by seibtph** [comment]
Mit der Version 2.7.1 sollte das Problem nun gelöst sein.

Wenn die fe_page_mate.html5 angepasst wurde, müsste folgende Zeile ...

```
$combiner->add('bundles/matetheme/sass/mate.scss');
```

durch folgende Zeilen ersetzt werden:

```
if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
    $combiner->add('bundles/matetheme/sass/mate_win.scss');
} else {
    $combiner->add('bundles/matetheme/sass/mate.scss');
}
```
