### ISSUE TITLE
Color Theme in rot

### ISSUE THREAD

**Issue by bixicy** [contao-themes-net/mate-theme-bundle#45]
Hallo,

gibt es bereits ein Farbset in rot? Ähnlich dem blauen oder grünen mit den sanften farbtönen?

**Comment by seibtph** [comment]
Du könntest einfach die Variablen der _custom_colors.scss anpassen, in der Dokumentation findest du dazu alles weiteres: https://docs.contao-themes.net/#/mate_theme/mate-farben-und-schriften.

Gegen eine Spende einer Entwicklungsstunde könnten wir das aber auch direkt in das MATE Theme integrieren: https://contao-themes.net/sponsoring.html.
