### ISSUE TITLE
Dropdown menu hidden by context menu on horizontal nav-bar and touchscreen

### ISSUE THREAD

**Issue by Ernestopheles** [contao-themes-net/mate-theme-bundle#46]
## Bug description
Using a touchscreen (10,5 inch, landscape) touching the horizontal navigation bar shows both, dropdown-menu and context-menu. So the dropdown-menu is not or only partly visible.

## Steps to reproduce
Go to www.zukunftsforum-rissen.de and touch the menuitem "Mitmachen".

## Expected behavior
Dropdown-menu visible

## Screenshots
![2020_03_17_14 49 16](https://user-images.githubusercontent.com/7561403/76862574-9d178400-685e-11ea-8ad8-ba5c7454ba48.jpg)

## Environment
Android 7.0 on galaxy tab s2 (same effect also on galaxy tab s5e) Chrome-browser
Hoster: linevast, php 7.3, maria-db

**Comment by seibtph** [comment]
Does the error still occur? I can't reproduze this.

**Comment by Ernestopheles** [comment]
yes, it does. You can also watch this behaviour on the MATE Live-Demo using a tablet computer

**Comment by seibtph** [comment]
Can't reproduze this on Android 7.1.1. Therefore I will close this issue. Feel free to reopen the issue if the error stills occur.
