### ISSUE TITLE
Slider / Tabbeschriftungen

### ISSUE THREAD

**Issue by Peresics** [contao-themes-net/mate-theme-bundle#48]
Hallo,

ich habe heute die neue Version eingespielt. Mir ist jetzt aufgefallen das bei den Tabbeschriftungen etwas nicht stimmt. Die Headline und Subheadline werden falsch dargestellt. 

Quelltext:
```
<span class="inner">
<span class="subheadline">Text 1<span class="headline">Text 2/span></span>
</span>
```
die Headline ist irgendwie in der subheadline gelandet. Liegt da ein Fehler auf unsere Seite oder hat das mit dem Update zu tun?

Grüße aus Wiesbaden

**Comment by seibtph** [comment]
Hallo @Peresics,

unter der MATE Theme Version 2.8.0 tritt der Fehler auf? Unter welcher Contao-Version? Hast du evtl. noch einen Link zur Seite? Leider konnte ich den Fehler bisher noch nicht reproduzieren.

**Comment by Peresics** [comment]
Hi,

habe heute den Verursacher gefunden. Es handel sich dabei um "heimrichhannot/contao-hyphenator-bundle". Als ich dies deinstallierte funktioniert alles wieder wie vorher. Da dies nach Update auf MateTheme (Version 2.8.0) passiert ist, vermute ich das diese jetzt nicht mehr richtig zusammenarbeiten. Vielleicht können Sie jetzt den Fehler nachvollziehen. Noch zur Info: Eine neue Version von den hyphenator-bundle hatte ich nicht installiert. Ich hatte vor und nach dem MateTheme-Update die Version  1.9.1 installiert.

**Comment by seibtph** [comment]
Ich habe mir das Problem mit dem contao-hyphenator-bundle angeschaut und konnte es lösen. In der Version 2.8.4 des MATE Theme ist der Fehler gefixt, dann sollten die Slider-Beschriftungen wieder ordentlich aussehen.
