### ISSUE TITLE
checkbox as mandatory field doesn't work

### ISSUE THREAD

**Issue by kFreigeist** [contao-themes-net/mate-theme-bundle#49]
## Bug description
In my form I have a checkbox as a mandatory field. When I mark it and send the form, the text "Please fill in the field!" appears. If I remove the checkmark in the backend in the mandatory field, I can send the form. But I need the checkbox as a mandatory field.

## Steps to reproduce
https://physiolang.kreative-freigeister.de/kontakt.html
When I sent an email to test.

## Expected behavior
The form will be sent when the checkbox is marked.

## Screenshots
![checkbox1](https://user-images.githubusercontent.com/64268735/80226651-ed97b380-864c-11ea-9f1f-9fda908577a8.png)
![checkbox2](https://user-images.githubusercontent.com/64268735/80226648-ec668680-864c-11ea-9d62-333eb6e67036.png)
![checkbox3](https://user-images.githubusercontent.com/64268735/80226655-ed97b380-864c-11ea-9c65-d5184f09b202.png)

## Environment
macOS Catalina, Version 10.15.3
PHP 7.2.24
Contao 4.9.0
Browser: Firefox Developer 76.0b5 and Chrome 80.0.3987.163

**Comment by seibtph** [comment]
You should set a value in the option, then the mandatory field works.
