### ISSUE TITLE
show google map

### ISSUE THREAD

**Issue by hbelow** [contao-themes-net/mate-theme-bundle#5]
I  included both packages in contao but in vain the google map does not show. is there any sample how to show the map instead of the picture?

**Comment by MDevster** [comment]
Can you please provide an example and name the extensions you use?

**Comment by hbelow** [comment]
Ist bereits obsolet. Trotzdem Danke!

Danke im Voraus!

Mit freundlichen Grüßen

ppa. Hans-Joachim Below sen.
HR Consultant




Sabine Below Personaldienstleistungen GmbH
Geschäftsführung: Sabine Below
Sitz der Gesellschaft ist Hamburg
Handelsregister: Amtsgericht Hamburg HRB 49363
Umsatzsteueridentifikationsnummer:
DE 118536084 Brandsende 2-4, 20095 Hamburg
Telefon: (040) 32 54 44 10
Fax: (040) 32 54 44 34
E-Mail: ab@below-personal.de
Internet: below-personal.de

Geschäftsführung: Sabine Below
Sitz der Gesellschaft ist Hamburg
Handelsregister: Amtsgericht Hamburg HRB 49363
Umsatzsteueridentifikationsnummer: DE 118536084

Unsere aktuellen Stellenangebote
<https://below-personal.de/kandidaten/offene-positionen/>

Diese eMail enthält vertrauliche und/oder rechtlich geschützte
Informationen. Wenn Sie nicht der richtige Adressat sind oder diese eMail
irrtümlich erhalten haben, informieren Sie bitte
sofort den Absender und vernichten Sie diese eMail. Das unerlaubte Kopieren
sowie die unbefugte Weitergabe dieser eMail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this e-mail in error)
please notify the sender immediately and destroy this e-mail. Any
unauthorised copying, disclosure or distribution of the material in this
e-mail is strictly forbidden.

Einwilligung und Widerruf gemäß EU-DS-GVO:

*Einwilligungserklärung*
*------------------------------*


Ich bin damit einverstanden, dass meine Daten der Sabine Below
Personaldienstleistungen GmbH zu folgenden Zwecken erhoben, verarbeitet und
genutzt sowie an Dienstleister weitergegeben bzw. übermittelt und dort
ebenfalls zu den folgenden Zwecken verarbeitet und genutzt werden:
Personalberatung
bzw. Vermittlung an einen Arbeitgeber. Diese Daten werden in Ihrem Auftrag
bis zum Erhalt eines Widerrufs für 3 Jahre gespeichert.
Ich bin darauf hingewiesen worden, dass die im Rahmen der vorstehend
genannten Zwecks erhobenen persönlichen Daten meiner Person unter Beachtung
des EU-DSGVO verarbeitet, genutzt und übermittelt werden.
Ich bin zudem darauf hingewiesen worden, dass die Erhebung, Verarbeitung
und Nutzung meiner Daten auf freiwilliger Basis erfolgt. Ferner, dass ich
mein Einverständnis ohne für mich nachteilige Folgen jederzeit mit Wirkung
für die Zukunft widerrufen kann.



*Widerruf*
*------------------------------*



Meine Widerrufserklärung werde ich richten an:
Sabine Below Personaldienstleistungen GmbH, Brandsende 2
<https://maps.google.com/?q=Brandsende+2&entry=gmail&source=g>-4, 20095
Hamburg,

E-Mail: kandidat@below-personal.de
Im Fall des Widerrufs werden mit dem Zugang meiner Widerrufserklärung meine
Daten bei Sabine Below Personaldienstleistungen GmbH gelöscht.






Am Do., 20. Sep. 2018 um 09:02 Uhr schrieb Mathias Arzberger <
notifications@github.com>:
