### ISSUE TITLE
The security question doesn't appear on the form

### ISSUE THREAD

**Issue by kFreigeist** [contao-themes-net/mate-theme-bundle#50]
## Bug description
I have created a new form field in the backend. Type: security query (Sicherheitsabfrage). However, this form field doesn't appear in the frontend.

## Steps to reproduce
I noticed that it didn't work when I reloaded the website after creating it in the backend and the security question didn't appear.
https://physiolang.kreative-freigeister.de/kontakt.html

## Expected behavior
That the created form field appears.

## Screenshots
![sicherheitsfrage1](https://user-images.githubusercontent.com/64268735/80228631-921af500-864f-11ea-9ce4-02b4e7fe330f.png)
![sicherheitsfrage2](https://user-images.githubusercontent.com/64268735/80228634-934c2200-864f-11ea-9349-2a98256a3927.png)
![checkbox2](https://user-images.githubusercontent.com/64268735/80228915-f8077c80-864f-11ea-8f84-5c50b9fd4322.png)

## Environment
macOS Catalina, Version 10.15.3
PHP 7.2.24
Contao 4.9.0
Browser: Firefox Developer 76.0b5 and Chrome 80.0.3987.163

**Comment by seibtph** [comment]
The security question is hidden by default since contao 4. The field is only displayed if a bot tries to fill it in.
