### ISSUE TITLE
changes in scss no changes in frontend

### ISSUE THREAD

**Issue by bixicy** [contao-themes-net/mate-theme-bundle#54]
Hi,

I changed in files/mate/sass/_custom_colors.scss to the blue design. I uncomment @import 'mate_color_schemes/mate_blue_colors';

After this I cleared the Symphony cache in Contao Manager and also all points in Backend System Maintanace. But nothing changed.

Do you have a hint to use the blue design?

**Comment by MDevster** [comment]
This is the right way! Is there somewhere I can take a look at it? Maybe the browser cache is the problem?

**Comment by bixicy** [comment]
At his moment its not public, I changed the PC, but also in green. And mobile also in green.

I deleted the cache in my browser also.

**Comment by MDevster** [comment]
How is your setup? Local, Windows, Linux, which web server, which PHP version, which MATE Theme version?

**Comment by MDevster** [comment]
I tested it again in our demo at https://mate.pdir.de/, it works as expected.
I do reload in Chrome via CTRL + F5. Have you tested privacy mode in your browser?

**Comment by bixicy** [comment]
Yes of course I refreshed several times via CTRL + F5

I published for the moment, but some parts are not complete finished.
https://bit.ly/3fVDDqP

If necessary, I can create a backend user

**Comment by MDevster** [comment]
You can send the backend user to support@pdir.de

**Comment by MDevster** [comment]
Probably problems creating the symlinks to include the color changes directly in the custom.scss has solved the problem.
