### ISSUE TITLE
Make theme usable for English language / Localizable Datepickers

### ISSUE THREAD

**Issue by amenk** [contao-themes-net/mate-theme-bundle#55]
Problem:

The theme assumes we are in a German locale by initializing the datepickers all German.

So how to overwrite the init code in

https://github.com/contao-themes-net/mate-theme-bundle/blob/master/src/Resources/public/js/theme.js#L9

**Comment by amenk** [comment]
Ideas from dirty to clean:

1. Overwrite https://github.com/contao-themes-net/mate-theme-bundle/blob/aa7ec6b97a159c5595ec4b7a9a7eec3559b82450/src/Resources/contao/templates/layouts/mate/fe_page_mate.html and remove the inclusion of theme.js

2. Somehow rewrite the theme, overlay a new theme.js with english config

3. extract the language specific code to a theme_en.js theme_de.js and so on, include by current language

**Comment by seibtph** [comment]
fixed in version 2.10.2.

You only need to update the theme.
