### ISSUE TITLE
Layout mit linker Spalte Menü aufklappen

### ISSUE THREAD

**Issue by samazaphikel** [contao-themes-net/mate-theme-bundle#56]
Hallo,

ich nutze auf einer Unterseite das Layout mit linker Spalte.

Ist es möglich, dass die Unterverzeichnisse alle automatisch aufgeklappt sind?

**Comment by seibtph** [comment]
Du kannst das einfach über folgende CSS-Anpassung in der custom.scss erreichen.

```
.subnav .dropdown-content {
    display: block;
}
```
