### ISSUE TITLE
Design changed back to default green

### ISSUE THREAD

**Issue by bixicy** [contao-themes-net/mate-theme-bundle#57]
Hi,

as I last time already mentioned https://github.com/contao-themes-net/mate-theme-bundle/issues/54

I updatetd Mate Theme from 2.9 to 2.11.3, and after update I dont have the blue design. The design changed back to green.

In filemanager in `mate/sass/_custom_colors.scss`, there is the import to `@import '_mate_blue_colors';`
and this file is in the same folder, but the design is not changing. I also copied the blue design variables in **_custom_colors.scss**, but its not changing.

I deleted the Smphony Cache and as well Backend Cache without any changes.

Could you tell me what you customized that the design has correctly changed?

Edit
After deleting the cache several times I have now copied the complete css code from the **_mate_blue_colors.scss** in the **_custom_colors.scss** Now it works. Something is probably wrong with the paths.

Firstly, the main menu can no longer be opened properly. Only if you move the mouse over the text in the menu, the bold line , it folds out. On the text it does not open. If one then tries to select the opened menu items, the menu closes immediately before one has the chance to click on it. So only as long as one stays on the line the menu is unfolded.

There are some more issues in the template Layout **default** and **Layout with left column**

I think the update has messed up the layout settings. And the menu is related to a JS file, maybe also from layout settings

**Comment by bixicy** [comment]
I changed back to my last Version 2.9 and found out, the Menu Issue is based on 2.11. On 2.9, is all ok.

**Comment by seibtph** [comment]
To import the blue colour scheme you should add this line:

`@import 'mate_color_schemes/mate_blue_colors';`

**This is wrong:**

`@import 'mate_blue_colors';`

I can't reproduze the navigation errors. Which browser do you use? Can you send a link to your page?

**Comment by bixicy** [comment]
Hi,
Mdevster created the import **@import '_mate_blue_colors';** in **mate/sass/_custom_colors.scss** in this ticket https://github.com/contao-themes-net/mate-theme-bundle/issues/54

And this is working at the moment.

I already downgradet to the older 2.9, so for this moment I cant send a link to this issue. Im using google chrome and firefox.

But on a fresh installation, only Mate theme installed. You can see the issue.

**Comment by seibtph** [comment]
@bixicy I can't see any issues with the navigation (also not in chrome or firefox). Can you reproduze this in the MATE demo? https://mate.pdir.de/ (this is the newest version)?
