### ISSUE TITLE
Boxen verrutschen wenn Zeile nicht vollständig gefüllt ist

### ISSUE THREAD

**Issue by ds0304** [contao-themes-net/mate-theme-bundle#58]
Hallo,

ich hoffe, dass dies der richtige Weg zur Kontaktaufnahme ist.
Wir arbeiten an einer neuen Schulhomepage und verwenden dafür das tolle mate-Theme!

Heute habe ich ein Update des Themes auf Version 2.11.3 durchgeführt. Nun fällt mir auf, dass bei mehrspaltigen Anordnungen die Boxen nicht mehr dort stehen, wo sie sein sollten, sofern eine Zeile nicht vollständig gefüllt ist.

Sehen kann man das z.B. auf folgenden Seiten:

https://contao.heinrich-boell-schule.de/aktuelles.html (erster Newskasten unten)
https://contao.heinrich-boell-schule.de/unsere-schule/unterricht/fachschaften.html (Alle Boxen der Fächer waren vorher von links nach rechts gefüllt)

Ist das ein Fehler im Theme? Oder habe ich unbewusst noch irgendetwas verstellt?

Viele Grüße
Daniel Schneider

**Comment by seibtph** [comment]
Hallo,

das ist tatsächlich ein Bug mit der letzten Version gewesen. Mit Version 2.11.4 sollte dieser nun behoben sein.
