### ISSUE TITLE
Problem mobile Navigation im Bereich zwischen 767 und 992 Pixel

### ISSUE THREAD

**Issue by mlwebworker** [contao-themes-net/mate-theme-bundle#59]
## Bug description
Unter 993 Pixel verschwindet die Hauptnavigation und der Button mobile Navigation sollte angezeigt werden. Das Element ist zwar da, sitzt aber viel zu weit unten und ist nicht sichtbar. Genau untersucht habe ich nicht wie es korrekt sein sollte, aber wenn man beim Selektor nav a.sidenav-trigger das display:flex; entfernt rutscht das Element in den Sichtbereich schon mal fast an die richtige Stelle. Beim Scrollen, ist der invertierte Button natürlich genauso betroffen (allerdings ist der sichtbar und nur zu tief). Unter 767px ist dann alles wieder korrekt. Getestet direkt auf Deiner Demoseite und in meiner Testinstallation unter Window 10 mit Firefox, Chrome und Edge (jeweils aktuellste Version).

## Steps to reproduce
Kann man in der Demo mit den Entwicklertools sehen

## Expected behavior
Getestet direkt auf der Demoseite und in meiner Testinstallation unter Windows 10 mit XAMPP und PHP 7.3 mit Firefox, Chrome und Edge (jeweils aktuellste Version).

## Screenshots
![2020-08-16_problem_mate_theme_1](https://user-images.githubusercontent.com/3602676/90340296-6f925a80-dff7-11ea-9edd-a0d1e99dd98c.jpg)
![2020-08-16_problem_mate_theme_2](https://user-images.githubusercontent.com/3602676/90340299-728d4b00-dff7-11ea-8821-291f134d6ea0.jpg)

**Comment by seibtph** [comment]
In Version 2.11.5 habe ich den Fehler behoben. In der Demo funktioniert es auch wieder. Danke für das Melden des Fehlers.
