### ISSUE TITLE
Problem mit Benutzergruppen

### ISSUE THREAD

**Issue by Katze75** [contao-themes-net/mate-theme-bundle#6]
Ich kann die Benutzergruppen nicht anlegen/editieren, bekomme Meldung  "Internal Server Error. 
Compile Error: Cannot declare class tl_theme_extended, because the name is already in use". Was kann mir helfen?

**Comment by MDevster** [comment]
@Katze75 Wie konntest du das Problem lösen? Eventuell kommt ja jemand anderes über die Suche auf dieses Ticket und hat das gleiche Problem.

**Comment by Katze75** [comment]
Während ich alle Caches etc. über Contao-Manager löschte, habe ich in einer Fehlermeldung gelesen, dass ich die Datei tl_theme.php zwei mal in /vendor/pdir/contao-theme-helper-bundle/src/Resources/contao/dca habe. Habe die doppelte Datei gelöscht und alles funktioniert wieder.
