### ISSUE TITLE
Layout defect After Update  2.9.1 -> 2.11.6 under Contao 4.9.7

### ISSUE THREAD

**Issue by Ernestopheles** [contao-themes-net/mate-theme-bundle#60]
After the update contents of the middle row is displayed in the left row. After scrolling down the page looks good again.
![Bildschirmfoto von 2020-09-29 23-38-56](https://user-images.githubusercontent.com/7561403/94619883-f18bc980-02ad-11eb-8c58-b3a68a0d4118.png)
![Bildschirmfoto von 2020-09-29 23-39-08](https://user-images.githubusercontent.com/7561403/94619888-f486ba00-02ad-11eb-87a7-f2fe5c359af3.png)

**Comment by seibtph** [comment]
I can't reproduze this. Maybe you can send a link from the page? I have tested this with the contao version 4.9.7 and mate theme version 2.11.6 and it works.

**Comment by Ernestopheles** [comment]
Thanks for testing. Here is the link (with mate theme not yet updated):
https://zukunftsforum-rissen.de/

Am Freitag, den 02.10.2020, 01:16 -0700 schrieb Philipp Seibt:

**Comment by seibtph** [comment]
I have tested this in our theme demo and it works. Maybe you can create a copy of your website? Have you made any customizations?

**Comment by Ernestopheles** [comment]
Thanks for answering.  On a test installation
https://www.zfr00.hs-example.de/ you will find the website with updatet
mate (to todays latest version), using Contao 4.10.4.

To compare you find the website with Mate 2.91 and Contao 4.9.7
www.zukunftsforum-rissen.de

best regards, ernst
Am Freitag, den 09.10.2020, 02:14 -0700 schrieb Philipp Seibt:

**Comment by seibtph** [comment]
You can fix this with a change in the custom.scss.

```
#container {
  width: 100%;
}
```

I can't see any difference to the demo page.

**Comment by Ernestopheles** [comment]
Danke, hat gut funktioniert.

Am Dienstag, den 27.10.2020, 11:27 +0000 schrieb Philipp Seibt:

**Comment by Ernestopheles** [comment]
Thnks for presenting a work around

**Comment by Ernestopheles** [comment]
Moin,

ein Fehler hat sich wohl doch mit dem Update eingeschlichen:

Bei Seitenlayout default blättert die Hauptnavigationsleiste nicht auf,
reagiert auch gar nicht auf Cursor over.




.Am Mittwoch, den 28.10.2020, 13:23 +0100 schrieb Ernst Jendritzki:
