### ISSUE TITLE
Darstellungsfehler bei Formularfeldern im Layout "default" im Farbschema Mate Dark

### ISSUE THREAD

**Issue by HeiBa69** [contao-themes-net/mate-theme-bundle#61]
## Bug description
Darstellungsfehler bei Formularfeldern (z.B. Kontaktformular) im Layout "default". Das jeweilige Formular hat einen weißen Hintergrund (korrekt), aber die Schriftfarbe beim Schreiben des Textes ist ebenfalls weiß (Fehler). Wenn man aus dem besagten Feld springt, sieht man den geschriebenen Text wieder, da er in weiße Farbe und der Hintergrund in schwarze Farbe wechselt. Dieser Fehler tritt nur im Layout "default" auf, bei den Layouts "linke Spalte", "rechte Spalte" und "linke und rechte Spalte" tritt dieses Verhalten nicht auf (siehe hierzu die Screenshots). 

## Steps to reproduce
Bei der Erstellung eines Kontaktformulars auf der Seite https://restaurant-kabineddle.de/kontakt.html. Es wurde das Farbschema Mate Dark genutzt. Es wurden keine individuellen Anpassungen am Farbschema vorgenommen. Der Fehler wurde in der Theme-Version 1.9.3 erkannt und ist auch noch in der aktuellen Version 2.11.7 so vorhanden.

## Expected behavior
Beim Schreiben des Feldinhaltes sollte der Text schwarz dargestellt werden, da ja der Feldhintergrund weiß eingefärbt ist. Bei Verlassen des Feldes sollte der Text weiß werden und der Feldhintergrund sich schwarz einfärben.

## Screenshots
Fehlerbild: ![Mate_Formular_Layout-default](https://user-images.githubusercontent.com/51930367/95869432-a2dd3580-0d6b-11eb-90bd-52fc2be89bb6.png)
Korrekte Darstellung (Layout linke Spalte): ![Mate_Formular_Layout-linke-Spalte](https://user-images.githubusercontent.com/51930367/95869549-c607e500-0d6b-11eb-8172-f73b7cf89b59.png)

## Environment
Client: Windows 10 Professional 2004, Server: Ubuntu 18.04.5 LTS‬ (aktuelle Updates), PHP 7.2.34, Contao 4.4.54, Browser Microsoft Edge 86.0.622.38

**Comment by seibtph** [comment]
Ich kann den Fehler leider nicht reproduzieren, habe es mit Contao 4.4.54 und der MATE Theme Version 2.11.7 getestet. Gern kannst du uns mal einen Contao-Zugang an support@pdir.de senden, wenn wir da mal hineinschauen sollen. 

Normalerweise sollte beim dunklen Farbschema der Hintergrund des Formularfelds immer schwarz und die Schrift weiß sein, egal ob man sich im oder außerhalb des Feldes befindet.

**Comment by seibtph** [comment]
Fehler wurde gelöst. Im Layout war unter CSS-Framework Formuare aktiv, weswegen das CSS überschrieben wurde.
