### ISSUE TITLE
Bildelement in ce_text für Großansicht nicht erreichbar

### ISSUE THREAD

**Issue by mlwebworker** [contao-themes-net/mate-theme-bundle#62]
## Bug description
Wird im Bildelement eine Liste verwendet ist das Bild nicht erreichbar, wenn es rechts positioniert ist.
Ursache sind die absoluten bzw. relativen Positionierungen der li-Elemente

siehe dazu https://community.contao.org/de/showthread.php?79354-MATE-Theme-Bild-mit-Gro%C3%9Fansicht&p=534578#post534578

## Expected behavior
Version des TO bei Contao kenne ich nicht.
Ich habe es in meiner Testinstallation nachvollziehen können
Contao 4.9.8
Mate-Theme: 2.12.0

Gerade auch noch mal die Testinstallation aktualisiert.
Das Problem tritt auch auf in
Contao 4.9.9
Mate-Theme 2.12.2

Und auch bei links platziertem Bild auf.
Bei der Platzierung links verschwinden dann auch noch Eure Elemente die den list-style-type "simulieren".

**Comment by seibtph** [comment]
Sollte jetzt mit Version 2.12.3 behoben sein.

**Comment by mlwebworker** [comment]
Super funktioniert.
