### ISSUE TITLE
Installation auf 4.10 fails

### ISSUE THREAD

**Issue by theking2** [contao-themes-net/mate-theme-bundle#64]
## Bug description
Mate theme cannot be installed

## Steps to reproduce
Searched and loaded the Mate Theme in contao-mananger

## Environment
PHP 7.4 Apache 2.4.41

Contao Manager Logfiles:
[logs.zip](https://github.com/contao-themes-net/mate-theme-bundle/files/5747211/logs.zip)

**Comment by seibtph** [comment]
Ich habe es mit Contao 4.9 und 4.10 und mit der aktuellsten MATE Theme Version getestet und da gab es keine Probleme. Besteht das Problem immer noch? Scheitert es bereits bei der Installation im Contao Manager?
