### ISSUE TITLE
Contao Frontent mit Mate Theme wird nicht geladen im Browser

### ISSUE THREAD

**Issue by freeemind** [contao-themes-net/mate-theme-bundle#66]
Hallo! 
Mittlerweile hab ich es auf 3 verschiedenen Accounts (2 versch. Provider (World4you und AllInkl) getestet und es wird nach der Installation von Contao und Mate (laut Anleitung), inkl. der Demodaten, nichts angezeigt ("...Zeitüberschreitung") bzw. das Frontend nicht geladen:
Testweb:
https://contao-mate-test2.bitstrom.at/
Contaoversion: 4.10.6

... das "Nature" Theme hat übrigens überall ohne Probleme auf Anhieb funktioniert.

Was könnte da sein?

Beste Grüße,
Roman

**Comment by seibtph** [comment]
Hallo Roman,

ich habe das jetzt nochmal in zwei Installationen getestet und da hat alles geklappt (auch mit Contao 4.10.6, mit der neuesten MATE Theme Version und lokal sowie bei All-Inkl). 

Wurde das MATE Theme ohne Probleme installiert? Sprich ist es im Contao Manager bei den Paketen zu sehen? 

Wurden die Demodaten erfolgreich importiert? Also sind Seiten, Artikel etc. im Backend angelegt worden? 

Ansonsten kannst du uns auch gern einen Contao Zugang zusenden, wenn wir dort mal hineinschauen sollen. Gern an support@pdir.de.

**Comment by freeemind** [comment]
Hallo Phillip,
ich danke dir für deine Antwort!

Es funktioniert!
Ich hab es jetzt nochmal getestet und "herumgespielt" und siehe da, der Fehler lag am (für den Test) nicht vorhandenen https -Zertifikat und der Einstellung im Contao Backend beim Startpunkt. Hier ist beim Mate-Theme nach frischer Installation  standardmäßig nämlich "https" eingestellt und beim Nature-Theme "http". In den Einstellungen geändert und das wars! :-)

Könnte man eventuell bei der Installations-Anleitung hinzufügen ;-)

Vielen Dank nochmal!

Beste Grüße,
Roman
