### ISSUE TITLE
englisch sprachige labels

### ISSUE THREAD

**Issue by cumulusk** [contao-themes-net/mate-theme-bundle#67]
## Bug description
die mate spezifischen templates z.B. event_mate_teaser greift nicht auf die englischen labels zurück. D.h. bei einer englisch sprachige website wird "Weiterlesen" anstelle von "Read more" angezeigt.

## Steps to reproduce
Auswahl von mate spezifische templates in Modulen.
Website root ist auf englisch eingestellt mit language fallback.
Auch mit Browser getestet, der auf en als bevorzugte Sprache eingestellt ist.

## Expected behavior
deutsche Labels bei deutscher website, englische bei englischer Website

## Screenshots
n/a

## Environment
Contao 4.10.6, Mate 2.12.17

**Comment by seibtph** [comment]
ist in Version 2.13.0 gefixt
