### ISSUE TITLE
Change colors to blue

### ISSUE THREAD

**Issue by hbelow** [contao-themes-net/mate-theme-bundle#68]
I have tried all possible alternatives in files/mate/ to convert green into blue, but in vain. Can somebody give a hint or two?

regards

hjb

**Comment by seibtph** [comment]
Did you comment out this line? 

`@import 'mate_color_schemes/mate_blue_colors';`

It should actually work with the latest version. Which contao and theme version do you have?

You may have to reload the page with Ctrl + F5.

**Comment by hbelow** [comment]
Moin, moin, yes I did  (contao 4.11/mate theme 1.4). Thks fr yr kind
support.



Hans-Joachim Below




Am Di., 2. März 2021 um 10:10 Uhr schrieb Philipp Seibt <
notifications@github.com>:

**Comment by hbelow** [comment]
Sorry the correct Mate theme version is 2.13.1



Hans-Joachim Below
HR Consultant

P +494032544410
E ab@below-personal.de
Sabine Below PDL GmbH
Brandsende 2-4
20095 Hamburg


Am Di., 2. März 2021 um 10:10 Uhr schrieb Philipp Seibt <
notifications@github.com>:

**Comment by hbelow** [comment]
Hi,
it works now, all colors are as planned. However I dont know why it
didnt work before. anyway thanks again for your kind assistance.

Hans-Joachim Below



Am Di., 2. März 2021 um 10:10 Uhr schrieb Philipp Seibt <
notifications@github.com>:

**Comment by MDevster** [comment]
Very nice that everything works now. I'll close the ticket now.
