### ISSUE TITLE
problem with the navbar - or a feature?

### ISSUE THREAD

**Issue by Totti1602** [contao-themes-net/mate-theme-bundle#71]
## Bug description

Folgenden Bug (?) konnte ich in der Demo und meiner eigenen Seite feststellen: Existiert eine Unterseite, so ist die Seite darüber über die Desktop Navigation nicht "klickbar" bzw. erreichbar. Erst ein "verstecken" der Unterseiten über die Seitenstruktur führt dazu, dass die darüberliegende Seite wieder klickbar ist. Zusätzlich klappen die unteren Ebenen der Navigation erst nach einem Klick aus, bisher genügte ein fahren mit dem Cursor über den jeweiligen Eintrag der Navigation. Es liegt offenbar ein Bug oder ein neues Feature in Verbindung mit der Navigation vor. Über die mobile Navigation funktioniert es hingegen wie bisher. 
## Steps to reproduce

Das Problem bzw. der Bug trat nach dem Update auf die neuste Version des Themes in Verbindung mit Contao 4.9.13 auf. Auf der Demoseite lässt sich dieser Bug über >Elemente >mate Elemente reproduzieren.
## Expected behavior

Meine Frage nun: Bug oder Feature bzw. ist es möglich den bisherigen Zustand des klickbaren Menüpunktes wieder herzustellen.
## Environment

Contao 4.9.13, neueste Version des Theme, PHP 7.4, Chrome & Edge

**Comment by Totti1602** [comment]
Eine Präzisierung: Das Problem tritt nur bei Windows 10 Geräten auf, welche über einen Touchscreen zur Eingabe besitzen (z.B. Microsoft Surface Pro und Go)

**Comment by seibtph** [comment]
In der Version 2.19.9 bzw. 3.0.1 sollte das nun behoben sein.
