### ISSUE TITLE
Changes in _custom_colors.scss and _custom_variables.scss has no effect why?

### ISSUE THREAD

**Issue by CarachoJon** [contao-themes-net/mate-theme-bundle#73]
## Bug description
Changes in _custom_colors.scss and _custom_variables.scss has no effect why?

Contao 4.9 LTS

**Comment by seibtph** [comment]
Did you reload the page with Ctrl + F5?

Can you post your _custom_colors.scss? Did you adjust the path to the file?

**Comment by CarachoJon** [comment]
Reload does not help. Deleting Browsercache doesnt helo too. But clear Scriptcache in the Contao Backend help. :) This would be a helpful information you should add to the .scss Files
