### ISSUE TITLE
Mate Theme Demobilder werden nicht angezeigt! 

### ISSUE THREAD

**Issue by iainmacnab** [contao-themes-net/mate-theme-bundle#78]
Contao 4.9.16 / PHP 7.4
Mate Theme (2.15.3) installiert wie immer, Symlinks neu erstellt usw - kein Demobilder. Die Bilder sind im Dateiverwaltung, werden aber nicht verlinkt.
- Verzeichnis mit den Bildern ist öffentlich gestellt
- var/cache/prod gelöscht und dann noch mal die Systemwartung ausgeführt
- Testlink: https://2021.autohaus-paepcke.de/

Zwei Fehlermeldungen:

[Thu Jul 08 00:27:24.473937 2021] [proxy_fcgi:error] -------------- AH01071: Got error 'PHP message: PHP Warning: is_dir() expects parameter 1 to be a valid path, string given in /var/www/vhosts/autohaus-paepcke.de/httpdocs/vendor/contao/core-bundle/src/Resources/contao/library/Contao/File.php on line 143PHP message: PHP Warning: file_exists() expects parameter 1 to be a valid path, string given in /var/www/vhosts/autohaus-paepcke.de/httpdocs/vendor/contao/core-bundle/src/Resources/contao/library/Contao/File.php on line 433PHP message: PHP Warning: file_exists() expects parameter 1 to be a valid path, string given in /var/www/vhosts/autohaus-paepcke.de/httpdocs/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Image.php on line 131', referer: https://2021.autohaus-paepcke.de/

bzw.

[2021-07-07 12:33:35] request.INFO: Matched route "contao_images". {"route":"contao_images","route_parameters":{"_rou te":"contao_images","_controller":"Contao\\CoreBun dle\\Controller\\ImagesController","_bypass_mainte nance":true,"path":"6/schlossbruecke-meissen-940d9272.jpg"},"request_uri":"https://2021.autohaus-paepcke.de/assets/images/6/schlossbruecke-meissen-940d9272.jpg","method":"GET"} []

Danke im Voraus

**Comment by seibtph** [comment]
Du könntest mal versuchen die Datenbank nochmal neu zu importieren. Also vorher die Datenbank leeren (bis auf die tl_user) und die SQL-Datei nochmal importieren. 

Schwierig zu sagen woran das liegt. Ich habe es nochmal bei uns getestet und da gab es keine Probleme.

**Comment by iainmacnab** [comment]
Danke - hat funktioniert! Kann es sein dass ich Installation Schritt 2 nicht so gemacht habe?
Danach noch NICHT auf Änderungen anwenden klicken, sondern erst die nächsten Schritte befolgen.

**Comment by seibtph** [comment]
Daran wird es nicht gelegen haben denke ich. Leider kann ich dir gar nicht sagen woran es gelegen haben könnte, aber wenn es jetzt funktioniert hat ist das ja gut. Normalerweise dürfte dieses Problem nicht auftreten. Falls es nochmal bei irgendjemanden auftritt, versuchen wir der Sache nochmal nachzugehen.
