### ISSUE TITLE
custom_colors` file not found for @import: materialize.scss on line 5, at column 1

### ISSUE THREAD

**Issue by RikeGeb** [contao-themes-net/mate-theme-bundle#79]
Hallo zusammen, 
ich baue gerade eine Webseite mit dem MATE-Thema auf, bisher hat auch alles ganz wunderbar geklappt, bis ich heute die Webseite aktuallsiert habe und folgender Fehler auftauchte: 

`../../../../../../../files/mate/sass/_custom_colors` file not found for @import: materialize.scss on line 5, at column 1
Call Stack:
#0 import materialize.scss mate.scss on line 1

Nun bin ich kein PHP-Profi, aber in den Einstellungen ist materialize.json schon seit beginn ausgewählt und bisher hat alles ganz Prima funktioniert. Wie kann ich diesen Fehler also beheben, ohne gleich alles Neu machen zu müssen? 

Vielen Dank schon mal für eure Hilfe! 

Ich arbeite mit Contao 4.9.16 und der MATE-Version 2.15.3 zusätzlich installiert ist noch MetaModels (in der aktuellen Version)

**Comment by seibtph** [comment]
In der aktuellen Version konnte ich den Fehler nicht reproduzieren.

Hast du irgendwelche Anpassungen vorgenommen? z. B. die Datei verschoben oder den Ordner mate umbenannt?

Du kannst uns sonst auch mal Zugangsdaten an support[AT]pdir.de senden, dann schauen wir gern mal hinein.

**Comment by RikeGeb** [comment]
Hallo,

zunächst: Vielen Dank für die schnelle Hilfe.

Ich habe in der custom.scss-Datei eine Änderung vorgenommen, sie aber sofort wieder rückgängig gemacht, jetzt ist die Datei wieder wie im Ursprung. Leider blieb der Fehler bestehen.

Ich habe euch einen Admin-Zugang an die ***@***.******@***.***> bereitgestellt.
Name: Mate-Support
KW: 2U9iYkZeEaPeerX

Mit freundlichen Grüßen / With kind regards
Friederike Gebauer
Medien- und Grafikdesign
Media- and Graphic Design

***@***.***D77887.8FB3C3C0]
Brökelner Straße. 8
37619 Bodenwerder
----------------------
Tel.: +49 (0) 55 33 / 93 48 10
Email: ***@***.******@***.***>
Web: www.leder-fiedler.de<http://www.leder-fiedler.de/>
----------------------
Registergericht Hildesheim, HRB 110785
USt-IdNr. DE 115 449 835
Geschäftsführer: Dennis Fiedler

Von: Philipp Seibt ***@***.***>
Gesendet: Dienstag, 13. Juli 2021 17:55
An: contao-themes-net/mate-theme-bundle ***@***.***>
Cc: Friederike Gebauer | LEDER-FIEDLER GmbH ***@***.***>; Author ***@***.***>
Betreff: Re: [contao-themes-net/mate-theme-bundle] custom_colors` file not found for @import: materialize.scss on line 5, at column 1 (#79)


In der aktuellen Version konnte ich den Fehler nicht reproduzieren.

Hast du irgendwelche Anpassungen vorgenommen? z. B. die Datei verschoben oder den Ordner mate umbenannt?

Du kannst uns sonst auch mal Zugangsdaten an support[AT]pdir.de senden, dann schauen wir gern mal hinein.

**Comment by RikeGeb** [comment]
Okaaay, nachdem ich nun das Thema neu synchronisiert habe, und die Tabelle geleert habe, ist die Vorschau und der Fehler scheint repariert.

Allerdings werden jetzt meine Farbeinstellungen aus der _custom_color.scss nicht mehr übernommen, gibt es für das 'Feature' eine Lösung? 
strg+f5 habe ich schon mehrfach ausprobiert und die Caches von Contao habe ich auch geleert. 

Und hinzukommend verschwinden die Bilder, wenn man nach ablauf einer gewissen Zeit von einem anderen Tab auf die Seite zurück wechselt. Sie kommen erst wieder, wenn die Seite neu geladen wird.

**Comment by MDevster** [comment]
Das klingt eher so als würde die Datei _custom_color.scss gar nicht geladen werden. Hast du einen Zugang für mich, dann kann ich mal nach schauen. Auch wegen dem Bilder Problem. Gern an support[AT]pdir.de

**Comment by RikeGeb** [comment]
@MDevster Zugangsdaten sind soeben rausgegangen.
