### ISSUE TITLE
Unterverzeichnisse klappen nicht mehr aus

### ISSUE THREAD

**Issue by jonasjoyless** [contao-themes-net/mate-theme-bundle#80]
Guten Tag,
ich habe Contao auf die Version 4.9.16 geupdatet und das Mate-Theme auf Version 2.15.3.
Seitdem klappen die Unterverzeichnisse im Layout mit linker Spalte nicht mehr aus.
Da ich sie auch standardmäßig ausgeklappt haben möchte, habe ich auch folgenden code in der custom.scss stehen:
`.subnav .dropdown-content {
    display: block;`
Vor dem updaten hat das so auch wunderbar funktioniert, jetzt leider nicht mehr.

Gruß,
Jonas

**Comment by seibtph** [comment]
Hallo Jonas,

das `display: block` reicht da nicht mehr ganz aus. 

So müsste es funktionieren:

```
.subnav .dropdown-content {
    display: block;
    visibility: visible;
    height: inherit;
    position: relative;
}
```

Ich konnte jetzt nicht ganz herausfinden mit welcher Version das sich geändert hatte, müsste aber schon ein Weilchen her sein.

**Comment by jonasjoyless** [comment]
So funktioniert es jetzt! Vielen Dank!
