### ISSUE TITLE
dependency material-icons-inserttag not supporting php8+

### ISSUE THREAD

**Issue by Orgoth** [contao-themes-net/mate-theme-bundle#88]
## Bug description
- contao-themes-net/material-icons-inserttag[1.0.0, ..., 1.0.2] require php ^5.6 || ^7.0 -> your php version (8.0.10.0) does not satisfy that requirement.

## Steps to reproduce
Try to install the package with PHP8.

## Expected behavior
Normal installation with PHP8 like 7.x. :)

## Screenshots
![Screenshot_20211018_174550](https://user-images.githubusercontent.com/1035170/137764983-bc0d5ea2-bb23-4a9a-883c-3d6841e6d6a6.png)

## Environment
all-ink.com - Webhosting
Linux dd39602 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64
PHP Version 8.0.10

**Comment by MDevster** [comment]
Version 1.1.0 of material-icons-inserttag is relased https://github.com/contao-themes-net/material-icons-inserttag/blob/master/CHANGELOG.md
