### ISSUE TITLE
Fehlermeldung bei SQL-Import

### ISSUE THREAD

**Issue by tswolf** [contao-themes-net/mate-theme-bundle#9]
Hallo liebe Theme-Entwickler,

ich wollte mir eben das Theme installieren und habe dabei jeden Schritt der echt guten Anleitung befolgt. Allerdings erhalte ich, egal was ich mache, einen Fehler beim Import der mitgelieferten SQL-Datei für Contao 4.4:

SQL-Befehl:
-- -- Daten für Tabelle `tl_article` -- INSERT INTO `tl_article` (`id`, `pid`, `sorting`, `tstamp`, `title`, `alias`, `author`, `inColumn`, `keywords`, `showTeaser`, `teaserCssID`, `teaser`, `printable`, `customTpl`, `protected`, `groups`, `guests`, `cssID`, `published`, `start`, `stop`, `pdir_th_tag`) VALUES (138, 107, 112, 1511436656, '05/03 footer section3', 'id-05-03-footer-section3', 1, 'main', NULL, '', 'a:2:{i:0;s:0:\"\";i:1;s:0:\"\";}', NULL, '', '', '', NULL, '', 'a:2:{i:0;s:0:\"\";i:1;s:0:\"\";}', '1', '', '', 'MATE05/03'), (137, 107, 96, 1511436650, '05/02 footer section2', 'id-05-02-footer-section2', 1, 'main', NULL, '', 'a:2:{i:0;s:0:\"\";i:1;s:0:\"\";}', NULL, '', '', '', NULL, '', 'a:2:{i:0;s:0:\"\";i:1;s:0:\"\";}', '1', '', '', 'MATE05/02'), (136, 107, 64, 1511436644, '05/01 footer section1', 'id-02-01-footer-section1', 1, 'main', NULL, '', 'a:2:{i:0;s:0:\"\";i:1;s:0:\"\";}', NULL, '', '', '', NULL, '', 'a:2:{i:0;s:0:\"\";i:1;s:0:\"\";}', '1', '', '', 'MATE05/01'), [...]

MySQL meldet:
#1062 - Duplicate entry '138' for key 'PRIMARY'

---
Die tl_files habe ich zuvor geleert und die truncation wurde mir vom PHPMyAdmin auch bestätigt.

Eine Idee, woran ich hier scheitere?

Beste Grüße,
Tom

**Comment by MDevster** [comment]
Hallo Tom,

der Fehler sagt das es bereits einen Eintrag mit der "id" 138 in der Tabelle "tl_article" gibt.
Sollte bei Dir bereits ein vorheriger Import schief gegangen sein, müsstest du vorher noch einmal die betroffenen/alle Tabellen leeren.
