### ISSUE TITLE
Klickbereich der Buttonelemente vergrößern

### ISSUE THREAD

**Issue by contaoacademy** [contao-themes-net/mate-theme-bundle#94]
## Bug description
Der Link bei Buttons funktioniert nur, wenn auf die Schrift geklickt wird.

## Steps to reproduce
Ein Hyperlink-Element um die Klasse "btn" erweitern
Im Frontend den Button klicken, allerdings außerhalb des Textes.

## Expected behavior
Button sollte über die gesamte Fläche klickbar sein.

## Screenshots
Siehe https://mate.pdir.de/inhaltselemente/textelemente.html und dann den Button.
![screen-20220209_0lULL8yi](https://user-images.githubusercontent.com/23719181/153271222-a369e9c1-920e-4d1c-b0e8-ec42a6d2689f.png)

**Comment by MDevster** [comment]
Fixed in version 2.19.0.
