### ISSUE TITLE
Contao 4.13.0 - Installation nicht möglich

### ISSUE THREAD

**Issue by MichaelSFD** [contao-themes-net/mate-theme-bundle#96]
Hallo,

nach "Nature" habe ich nun auch versucht "ODD" und "MATE" unter Contao 4.13.0 zu installieren. Leider auch hier beide Male erfolglos.

"MATE" bricht bereits während der Installation ab. Screenshot in Anlage.

Bei "ODD" passiert dasselbe wie bei "Nature". Will man das Frontend aufrufen, kommt bei jeder Seite die Contao-Fehlerseite "Es ist ein Fehler aufgetreten".

Auch hier ist in der Dateiverwaltung der Ordner "odd" leer.

Ich nutze als öffentlichen Ordner "public", nicht "web".
PHP-Version ist 7.4.

Schon mal vielen Dank und viele Grüße

Michael

![mate](https://user-images.githubusercontent.com/100707911/156887709-877f19f1-a1c1-4753-9494-9dafbb7e97db.png)

**Comment by analogwerk** [comment]
Dieses Problem kann ich definitiv bestätigen - versuche auch seit gestern eine Installation. Auf 2 verschiedenen Hosts, sowohl mit PHP8 und PHP7.4 schlägt die Installation fehl.

**Comment by MDevster** [comment]
Hi @MichaelSFD,
hi @analogwerk,
contao.bootstrap/grid wurde noch nicht für Contao 4.13 LTS oder PHP 8 freigeben, daher treten diese Probleme auf. Wir haben uns entschieden die Erweiterung zu entfernen und eine Version 3.0.0 ohne diese Abhänigkeit zu veröffentlichen. Ihr könnt gern den Branch https://github.com/contao-themes-net/mate-theme-bundle/tree/php-8-support installieren und testen. Ich denke das wir Morgen die neue Version veröffentlichen können, wenn auch die Dokumentation unter https://pdir.de/docs/de/contao/themes/mate/update/ aktuliaisert wurde.

**Comment by MichaelSFD** [comment]
Hallo Matthias,

vielen Dank für die Rückmeldung.

Ich hatte "Mate" und auch "ODD" nur installiert, um zu sehen, ob es da die gleichen Probleme gibt, wie bei "Nature".

Kannst du mir zu "Nature" was zum Stand der Dinge was sagen?

Vielen Dank und viele Grüße

Michael

**Comment by MDevster** [comment]
Mit Version 2.18.0 sollte es nun keine Probleme mehr geben.
