### ISSUE TITLE
add default stylesheets 

### ISSUE THREAD

**Issue by MDevster** [contao-themes-net/mate-theme-bundle#98]
Text Align
These classes are for horizontally aligning content: `.left-align`, `.right-align` and `.center-align`.

Spacing -> Padding, Margin
Where property is one of:

    m - for classes that set margin
    p - for classes that set padding

Where sides is one of:

    t - for classes that set margin-top or padding-top
    b - for classes that set margin-bottom or padding-bottom
    l - for classes that set margin-left or padding-left
    r - for classes that set margin-right or padding-right
    x - for classes that set both *-left and *-right
    y - for classes that set both *-top and *-bottom
    blank - for classes that set a margin or padding on all 4 sides of the element

Where size is one of:

    0 - for classes that eliminate the margin or padding by setting it to 0
    1 - (by default) for classes that set the margin or padding to $spacer * .25
    2 - (by default) for classes that set the margin or padding to $spacer * .5
    3 - (by default) for classes that set the margin or padding to $spacer
    4 - (by default) for classes that set the margin or padding to $spacer * 1.5
    5 - (by default) for classes that set the margin or padding to $spacer * 3
    auto - for classes that set the margin to auto

**Example**
```
.mt-0 {
  margin-top: 0 !important;
}

.ml-1 {
  margin-left: ($spacer * .25) !important;
}

.px-2 {
  padding-left: ($spacer * .5) !important;
  padding-right: ($spacer * .5) !important;
}

.p-3 {
  padding: $spacer !important;
}
```

**Comment by seibtph** [comment]
You can use the spacing helpers to set margin and padding.

https://pdir.de/docs/de/contao/themes/mate/customization/helpers/
